/*
 * JTabbedPaneProjet.java
 *
 * Created on 26 janvier 2005, 02:53
 */

package P2S.UI.View;

import P2S.Control.Bundle.Bundle;
import P2S.Model.Projet;
import P2S.UI.View.JPanel.JPanelInfoGenProjet;
import P2S.UI.View.JPanel.JPanelInfoProbleme;
import P2S.UI.View.JPanel.JPanelInfoRisque;
import P2S.UI.View.JPanel.JPanelInfoSeuil;
import javax.swing.JTabbedPane;

/**
 * jtabbedpane pour un projet permettant de naviguer entre les differentes informations d'un projet
 * @author Fabien
 */
public class JTabbedPaneProjet extends JTabbedPane {
    
    /**
     * Creates new form BeanForm
     * @param proj proj a afficher
     */
    public JTabbedPaneProjet(Projet proj) {
        initComponents();
        
        this.addTab(Bundle.getText("JTabbedPaneProjet_TabInfoGen"), new javax.swing.ImageIcon(getClass().getResource("/P2S/Resources/tab_info.gif")), new JPanelInfoGenProjet(proj));
        this.addTab(Bundle.getText("JTabbedPaneProjet_TabRisques"), new javax.swing.ImageIcon(getClass().getResource("/P2S/Resources/tab_risk.gif")),new JPanelInfoRisque(proj.getListeRisques()));
	this.addTab(Bundle.getText("JTabbedPaneProjet_TabProblemes"), new javax.swing.ImageIcon(getClass().getResource("/P2S/Resources/tab_problemes.gif")),new JPanelInfoProbleme(proj.getListeProblemes()));
        this.addTab(Bundle.getText("JTabbedPaneProjet_TabSeuils"), new javax.swing.ImageIcon(getClass().getResource("/P2S/Resources/")),new JPanelInfoSeuil(proj));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
