/*
 * JTabbedPaneMembre.java
 *
 * Created on 26 janvier 2005, 15:45
 */

package P2S.UI.View;

import P2S.Control.Bundle.Bundle;
import P2S.Model.Membre;
import P2S.UI.View.JPanel.JPanelInfoGenMembre;
import javax.swing.JTabbedPane;

/**
 *
 * @author  Fabien
 */
public class JTabbedPaneMembre extends JTabbedPane {
    
    /** Creates new form BeanForm */
    public JTabbedPaneMembre(Membre membre) {
        initComponents();
        
        this.addTab(Bundle.getText("JTabbedPaneMembre_TabInfoGen"),new JPanelInfoGenMembre(membre));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
