/*
 * JTabbedPaneProjet.java
 *
 * Created on 26 janvier 2005, 02:53
 */

package P2S.UI.View;

import P2S.Control.Bundle.Bundle;
import P2S.Model.Projet;
import P2S.UI.View.JPanel.JPanelInfoGenProjet;
import javax.swing.JTabbedPane;

/**
 *
 * @author  Fabien
 */
public class JTabbedPaneProjet extends JTabbedPane {
    
    /** Creates new form BeanForm */
    public JTabbedPaneProjet(Projet proj) {
        initComponents();
        
        this.addTab(Bundle.getText("JTabbedPaneProjet_TabInfoGen"),new JPanelInfoGenProjet(proj));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
