/*
 * JTabbedPaneMembre.java
 *
 * Created on 26 janvier 2005, 15:45
 */

package P2S.UI.View;

import P2S.Control.Bundle.Bundle;
import P2S.Model.Membre;
import P2S.UI.View.JPanel.JPanelIndicArtefactsMembre;
import P2S.UI.View.JPanel.JPanelInfoGenMembre;
import P2S.UI.View.JPanel.JPanelIndicTachesMembre;
import P2S.UI.View.JPanel.JPanelInfoProfMembre;
import javax.swing.JTabbedPane;

/**
 * jtabbedpane pour un membre permettant de naviguer entre les differentes informations d'un membre
 * @author Fabien
 */
public class JTabbedPaneMembre extends JTabbedPane {
    
    /**
     * Creates new form BeanForm
     * @param membre membre a afficher
     */
    public JTabbedPaneMembre(Membre membre) {
        initComponents();
        
        this.addTab(Bundle.getText("JTabbedPaneMembre_TabInfoGen"), new javax.swing.ImageIcon(getClass().getResource("/P2S/Resources/tab_info.gif")), new JPanelInfoGenMembre(membre));
        this.addTab(Bundle.getText("JTabbedPaneMembre_TabTaches"),new javax.swing.ImageIcon(getClass().getResource("/P2S/Resources/tab_tasks.gif")), new JPanelIndicTachesMembre(membre.getListeTaches()));
        this.addTab(Bundle.getText("JTabbedPaneMembre_TabArtefacts"), new javax.swing.ImageIcon(getClass().getResource("/P2S/Resources/tab_artefacts.gif")), new JPanelIndicArtefactsMembre(membre.getListeArtefacts()));
        this.addTab(Bundle.getText("JTabbedPaneMembre_TabInfoProf"), new JPanelInfoProfMembre(membre.getListeRoles(), membre.getListeProjets()));
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
