/*
 * JDialogPremiereFois.java
 *
 * Created on 18 mars 2005, 23:15
 */

package P2S.UI.View.JDialog;

import P2S.Control.Bundle.Bundle;

/**
 *
 * @author  Fabien
 */
public class JDialogPremiereFois extends javax.swing.JDialog {
    
    /** Creates new form JDialogPremiereFois */
    public JDialogPremiereFois(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initTexte();
        this.jTextFieldHote.setText(P2S.P2S.Preferences.getProperty("host"));
        this.jTextFieldPort.setText(P2S.P2S.Preferences.getProperty("port"));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelHote = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jTextFieldHote = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("C'est la premi\u00e8re fois que vous utilisez P2S.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setText("Veuillez sp\u00e9cifier les informations n\u00e9cessaires pour la connexion avec le serveur");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        jLabelHote.setText("Hote : ");
        getContentPane().add(jLabelHote, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabelPort.setText("Port : ");
        getContentPane().add(jLabelPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        getContentPane().add(jTextFieldHote, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 170, -1));

        getContentPane().add(jTextFieldPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 170, -1));

        jLabel3.setText("Si ces informations changent,");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        jLabel4.setText("il sera possible de les modifier en \u00e9ditant le fichier preferences.properties");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel5.setText("situ\u00e9 \u00e0 la racine de P2S");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        getContentPane().add(jButtonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        getContentPane().add(jButtonAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-440)/2, (screenSize.height-306)/2, 440, 306);
    }//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        this.hide();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonAnnulerActionPerformed
    
    private void initTexte()
    {
        this.setTitle(Bundle.getText("JDialogPremiereFois_Title"));
        this.jLabel1.setText(Bundle.getText("JDialogPremiereFois_Jlabel1"));
        this.jLabel2.setText(Bundle.getText("JDialogPremiereFois_Jlabel2"));
        this.jLabel3.setText(Bundle.getText("JDialogPremiereFois_Jlabel3"));
        this.jLabel4.setText(Bundle.getText("JDialogPremiereFois_Jlabel4"));
        this.jLabel5.setText(Bundle.getText("JDialogPremiereFois_Jlabel5"));
        this.jLabelHote.setText(Bundle.getText("JDialogPremiereFois_JLabelHost"));
        this.jLabelPort.setText(Bundle.getText("JDialogPremiereFois_JLabelPort"));
        this.jButtonOK.setText(Bundle.getText("JDialogPremiereFois_JButtonOK"));
        this.jButtonAnnuler.setText(Bundle.getText("JDialogPremiereFois_JButtonAnnuler"));
    }
    
    public String getHote(){
        return this.jTextFieldHote.getText();
    }
    
    public String getPort(){
        return this.jTextFieldPort.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelHote;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JTextField jTextFieldHote;
    private javax.swing.JTextField jTextFieldPort;
    // End of variables declaration//GEN-END:variables
    
}
