package P2S.UI.View.JDialog;

import P2S.UI.View.*;
import P2S.Model.*;
import P2S.Control.Bundle.*;
import java.util.*;

/**
 *
 * @author  Fabien
 */
public class JDialogCreerProjet extends javax.swing.JDialog {
        
    private Vector _listeMesures;
    private String[] _titreColonnes;
    
    /** Creates new form JDialogCreerProjet */
    public JDialogCreerProjet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        _listeMesures = new Vector();
        
        // Initialisation de la table des mesures
        Object donnees[][] = new Object[0][0];
        _titreColonnes = new String[3];
        _titreColonnes[0] = Bundle.getText("JDialogCreerProjet_JTable_NomCol1");
        _titreColonnes[1] = Bundle.getText("JDialogCreerProjet_JTable_NomCol2");
        _titreColonnes[2] = Bundle.getText("JDialogCreerProjet_JTable_NomCol3");
                             
        this.jTableMesures.setModel(new ModeleTableMesure(donnees,_titreColonnes));
        
        this.initText();

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        JLabelNom = new javax.swing.JLabel();
        JLabelDateDebut = new javax.swing.JLabel();
        JTextFieldDateDebutJour = new javax.swing.JTextField();
        JLabelDateFin = new javax.swing.JLabel();
        JTextFieldDateFinMois = new javax.swing.JTextField();
        JLabelMesures = new javax.swing.JLabel();
        JScrollPaneMesures = new javax.swing.JScrollPane();
        jTableMesures = new javax.swing.JTable();
        JButtonOk = new javax.swing.JButton();
        JButtonAnnuler = new javax.swing.JButton();
        JButtonAjouterMesure = new javax.swing.JButton();
        JTextFieldNom = new javax.swing.JTextField();
        JTextFieldDateDebutMois = new javax.swing.JTextField();
        JTextFieldDateDebutAnnee = new javax.swing.JTextField();
        JTextFieldDateFinAnnee = new javax.swing.JTextField();
        JTextFieldDateFinJour = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        JLabelNom.setText("Nom du projet :");
        getContentPane().add(JLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        JLabelDateDebut.setText("Date de d\u00e9but :");
        getContentPane().add(JLabelDateDebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        JTextFieldDateDebutJour.setText("jj");
        getContentPane().add(JTextFieldDateDebutJour, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 30, -1));

        JLabelDateFin.setText("Date de fin :");
        getContentPane().add(JLabelDateFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        JTextFieldDateFinMois.setText("mm");
        getContentPane().add(JTextFieldDateFinMois, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 30, -1));

        JLabelMesures.setText("Mesures :");
        getContentPane().add(JLabelMesures, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        JScrollPaneMesures.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        JScrollPaneMesures.setBackground(new java.awt.Color(255, 255, 255));
        jTableMesures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JScrollPaneMesures.setViewportView(jTableMesures);

        getContentPane().add(JScrollPaneMesures, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 400, 110));

        JButtonOk.setText("OK");
        JButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonOkActionPerformed(evt);
            }
        });

        getContentPane().add(JButtonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        JButtonAnnuler.setText("Annuler");
        JButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAnnulerActionPerformed(evt);
            }
        });

        getContentPane().add(JButtonAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        JButtonAjouterMesure.setText("Ajouter mesure");
        JButtonAjouterMesure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAjouterMesureActionPerformed(evt);
            }
        });

        getContentPane().add(JButtonAjouterMesure, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 110, -1));

        getContentPane().add(JTextFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        JTextFieldDateDebutMois.setText("mm");
        getContentPane().add(JTextFieldDateDebutMois, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 30, -1));

        JTextFieldDateDebutAnnee.setText("aaaa");
        getContentPane().add(JTextFieldDateDebutAnnee, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 40, -1));

        JTextFieldDateFinAnnee.setText("aaaa");
        getContentPane().add(JTextFieldDateFinAnnee, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 40, -1));

        JTextFieldDateFinJour.setText("jj");
        getContentPane().add(JTextFieldDateFinJour, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 30, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-498)/2, (screenSize.height-325)/2, 498, 325);
    }//GEN-END:initComponents

    public void initText()
    {
        this.setTitle(Bundle.getText("JDialogCreerProjet_TitreFenetre"));
        
        JLabelNom.setText(Bundle.getText("JDialogCreerProjet_JLabel_Nom"));
        JLabelDateDebut.setText(Bundle.getText("JDialogCreerProjet_JLabel_DateDebut"));
        JLabelDateFin.setText(Bundle.getText("JDialogCreerProjet_JLabel_DateFin"));
        JLabelMesures.setText(Bundle.getText("JDialogCreerProjet_JLabel_Mesures"));
        JButtonOk.setText(Bundle.getText("JDialogCreerProjet_JButton_Ok"));
        JButtonAnnuler.setText(Bundle.getText("JDialogCreerProjet_JButton_Annuler"));
        JButtonAjouterMesure.setText(Bundle.getText("JDialogCreerProjet_JButton_AjouterMesure"));
        JTextFieldDateDebutJour.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateDebutJour"));
        JTextFieldDateDebutMois.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateDebutMois"));
        JTextFieldDateDebutAnnee.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateDebutAnnee"));
        JTextFieldDateFinJour.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateFinJour"));
        JTextFieldDateFinMois.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateFinMois"));
        JTextFieldDateFinAnnee.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateFinAnnee"));
    }
    
    private void JButtonAjouterMesureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAjouterMesureActionPerformed
        new JDialogAjoutMesure((JFrameP2S)(this.getParent()),true).show();       
    }//GEN-LAST:event_JButtonAjouterMesureActionPerformed

    private void JButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_JButtonAnnulerActionPerformed

    private void JButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonOkActionPerformed
        if(this.JTextFieldNom.getText().compareTo("") != 0)
            /*&&  this.JTextFieldDateDebutJour.getText().compareTo("") != 0 && this.JTextFieldDateDebutJour.getText().compareTo(Bundle.getText("JDialogCreerProjet_JTextField_DateDebutJour")) != 0
            &&  this.JTextFieldDateDebutMois.getText().compareTo("") != 0 && this.JTextFieldDateDebutMois.getText().compareTo(Bundle.getText("JDialogCreerProjet_JTextField_DateDebutMois")) != 0
            &&  this.JTextFieldDateDebutAnnee.getText().compareTo("") != 0 && this.JTextFieldDateDebutAnnee.getText().compareTo(Bundle.getText("JDialogCreerProjet_JTextField_DateDebutAnnee")) != 0
            &&  this.JTextFieldDateFinJour.getText().compareTo("") != 0 && this.JTextFieldDateFinJour.getText().compareTo(Bundle.getText("JDialogCreerProjet_JTextField_DateFinJour")) != 0
            &&  this.JTextFieldDateFinMois.getText().compareTo("") != 0 && this.JTextFieldDateFinMois.getText().compareTo(Bundle.getText("JDialogCreerProjet_JTextField_DateFinMois")) != 0
            &&  this.JTextFieldDateFinAnnee.getText().compareTo("") != 0 && this.JTextFieldDateFinAnnee.getText().compareTo(Bundle.getText("JDialogCreerProjet_JTextField_DateFinAnnee")) != 0)*/
        {
           // Date dateDebut = new Date(new Integer(this.JTextFieldDateDebutAnnee.getText()).intValue(),new Integer(this.JTextFieldDateDebutMois.getText()).intValue(),new Integer(this.JTextFieldDateDebutJour.getText()).intValue());
            //Date dateFin = new Date(new Integer(this.JTextFieldDateFinAnnee.getText()).intValue(),new Integer(this.JTextFieldDateFinMois.getText()).intValue(),new Integer(this.JTextFieldDateFinJour.getText()).intValue());
            ((JFrameP2S)this.getParent()).ajouterProjet(new Projet(this.JTextFieldNom.getText(),_listeMesures));
        }
        this.dispose();
    }//GEN-LAST:event_JButtonOkActionPerformed
    
    public void ajouterMesure(Mesure mesure)
    {
        _listeMesures.add(mesure);
    }
    
    public void rafarichirMesures()
    {
        Object donnees[][] = new Object[_listeMesures.size()][3];
        
        for(int i=0;i<_listeMesures.size();i++)
        {
            donnees[i][0] = ((Mesure)(_listeMesures.get(i))).get_nom();
            donnees[i][1] = new Integer(((Mesure)(_listeMesures.get(i))).get_limiteInf());
            donnees[i][2] = new Integer(((Mesure)(_listeMesures.get(i))).get_limiteSup());
        }
        this.jTableMesures.setModel(new ModeleTableMesure(donnees,_titreColonnes));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAjouterMesure;
    private javax.swing.JButton JButtonAnnuler;
    private javax.swing.JButton JButtonOk;
    private javax.swing.JLabel JLabelDateDebut;
    private javax.swing.JLabel JLabelDateFin;
    private javax.swing.JLabel JLabelMesures;
    private javax.swing.JLabel JLabelNom;
    private javax.swing.JScrollPane JScrollPaneMesures;
    private javax.swing.JTextField JTextFieldDateDebutAnnee;
    private javax.swing.JTextField JTextFieldDateDebutJour;
    private javax.swing.JTextField JTextFieldDateDebutMois;
    private javax.swing.JTextField JTextFieldDateFinAnnee;
    private javax.swing.JTextField JTextFieldDateFinJour;
    private javax.swing.JTextField JTextFieldDateFinMois;
    private javax.swing.JTextField JTextFieldNom;
    private javax.swing.JTable jTableMesures;
    // End of variables declaration//GEN-END:variables
    
}
