package P2S.UI.View.JDialog;

import P2S.Control.Bundle.*;
import P2S.Model.*;
import P2S.UI.View.*;
import java.text.DateFormat;
import java.util.Locale;

/**
 *
 * @author  kassem
 */
public class JDialogDetailTache extends javax.swing.JDialog {
    
    /** Creates new form JDialogAjoutMesure */
    public JDialogDetailTache(java.awt.Frame parent, boolean modal, Tache tacheDetail) {
        super(parent, modal);
        initComponents();
       
        this.initText();
        DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.FULL, Locale.getDefault());
        this.textIndNom.setText(tacheDetail.getNom());
        this.textIndRealisateur.setText((tacheDetail.getRealisateur()).getNom());
        this.textDescription.setText(tacheDetail.getDescription());
        this.textIndCharge.setText(new Integer(tacheDetail.getChargePrevue()).toString());
        this.textIndTempsPasse.setText(new Integer(tacheDetail.getTempsPasse()).toString());
        this.textIndTempsRestant.setText(new Integer(tacheDetail.getResteAPasser()).toString());
        this.textIndDateDebutPrevue.setText(dateFormat.format(tacheDetail.getDateDebutPrevue()));
        this.textIndDateDebutReelle.setText(dateFormat.format(tacheDetail.getDateDebutReelle()));
        this.textIndDateFinPrevue.setText(dateFormat.format(tacheDetail.getDateFinPrevue()));
        this.textIndDateFinReelle.setText(dateFormat.format(tacheDetail.getDateFinReelle()));
        this.textIndEtat.setText(new Integer(tacheDetail.getEtat()).toString());
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        labelStaticIndNom = new javax.swing.JLabel();
        textIndNom = new javax.swing.JTextField();
        labelStaticIndEtat = new javax.swing.JLabel();
        textIndEtat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textDescription = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        textIndRealisateur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textIndCharge = new javax.swing.JTextField();
        labelStaticIndTpsPasse = new javax.swing.JLabel();
        textIndTempsPasse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textIndTempsRestant = new javax.swing.JTextField();
        labelStaticIndDatePrevue = new javax.swing.JLabel();
        textIndDateDebutPrevue = new javax.swing.JTextField();
        labelStaticIndDateDebutReelle = new javax.swing.JLabel();
        textIndDateDebutReelle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textIndDateFinPrevue = new javax.swing.JTextField();
        labelStaticIndDateFinReelle = new javax.swing.JLabel();
        textIndDateFinReelle = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        labelStaticIndNom.setText("Nom :");
        getContentPane().add(labelStaticIndNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        textIndNom.setBackground(new java.awt.Color(255, 255, 255));
        textIndNom.setEditable(false);
        textIndNom.setText("nom");
        textIndNom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 170, -1));

        labelStaticIndEtat.setText("Etat :");
        getContentPane().add(labelStaticIndEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, -1));

        textIndEtat.setBackground(new java.awt.Color(255, 255, 255));
        textIndEtat.setEditable(false);
        textIndEtat.setText("etat");
        textIndEtat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndEtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 70, -1));

        jLabel1.setText("Description :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, -1));

        textDescription.setEditable(false);
        textDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 170, 50));

        jLabel2.setText("R\u00e9alisateur :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        textIndRealisateur.setBackground(new java.awt.Color(255, 255, 255));
        textIndRealisateur.setEditable(false);
        textIndRealisateur.setText("reallisateur");
        textIndRealisateur.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndRealisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, -1));

        jLabel3.setText("Charge pr\u00e9vue :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, -1));

        textIndCharge.setBackground(new java.awt.Color(255, 255, 255));
        textIndCharge.setEditable(false);
        textIndCharge.setText("charge");
        textIndCharge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 70, -1));

        labelStaticIndTpsPasse.setText("Temps pass\u00e9 :");
        getContentPane().add(labelStaticIndTpsPasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, -1));

        textIndTempsPasse.setBackground(new java.awt.Color(255, 255, 255));
        textIndTempsPasse.setEditable(false);
        textIndTempsPasse.setText("temps pass\u00e9");
        textIndTempsPasse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndTempsPasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 70, -1));

        jLabel4.setText("Temps Restant :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, -1));

        textIndTempsRestant.setBackground(new java.awt.Color(255, 255, 255));
        textIndTempsRestant.setEditable(false);
        textIndTempsRestant.setText("restant");
        textIndTempsRestant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndTempsRestant, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 70, -1));

        labelStaticIndDatePrevue.setText("Date d\u00e9but pr\u00e9vue :");
        getContentPane().add(labelStaticIndDatePrevue, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, -1));

        textIndDateDebutPrevue.setBackground(new java.awt.Color(255, 255, 255));
        textIndDateDebutPrevue.setEditable(false);
        textIndDateDebutPrevue.setText("date pr\u00e9vue");
        textIndDateDebutPrevue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndDateDebutPrevue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 70, -1));

        labelStaticIndDateDebutReelle.setText("Date d\u00e9but r\u00e9elle :");
        getContentPane().add(labelStaticIndDateDebutReelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, -1));

        textIndDateDebutReelle.setBackground(new java.awt.Color(255, 255, 255));
        textIndDateDebutReelle.setEditable(false);
        textIndDateDebutReelle.setText("date r\u00e9elle");
        textIndDateDebutReelle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndDateDebutReelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 70, -1));

        jLabel5.setText("Date fin pr\u00e9vue :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, -1));

        textIndDateFinPrevue.setBackground(new java.awt.Color(255, 255, 255));
        textIndDateFinPrevue.setEditable(false);
        textIndDateFinPrevue.setText("date fin");
        textIndDateFinPrevue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndDateFinPrevue, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 70, -1));

        labelStaticIndDateFinReelle.setText("Date fin r\u00e9elle :");
        getContentPane().add(labelStaticIndDateFinReelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, -1));

        textIndDateFinReelle.setBackground(new java.awt.Color(255, 255, 255));
        textIndDateFinReelle.setEditable(false);
        textIndDateFinReelle.setText("date fin r\u00e9elle");
        textIndDateFinReelle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndDateFinReelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 70, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-400)/2, 400, 400);
    }//GEN-END:initComponents

    public void initText()
    {
        /*this.setTitle(Bundle.getText("JDialogAjouterMesure_TitreFenetre"));
        
        JLabelNom.setText(Bundle.getText("JDialogAjouterMesure_JLabel_Nom"));
        JLabelLimiteInf.setText(Bundle.getText("JDialogAjouterMesure_JLabel_LimiteInf"));
        JLabelLimiteSup.setText(Bundle.getText("JDialogAjouterMesure_JLabel_LimiteSup"));
        JLabelDescription.setText(Bundle.getText("JDialogAjouterMesure_JLabel_Description"));
        JButtonOk.setText(Bundle.getText("JDialogAjouterMesure_JButton_Ok"));
        JButtonAnnuler.setText(Bundle.getText("JDialogAjouterMesure_JButton_Annuler")); */       
    }
    
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelStaticIndDateDebutReelle;
    private javax.swing.JLabel labelStaticIndDateFinReelle;
    private javax.swing.JLabel labelStaticIndDatePrevue;
    private javax.swing.JLabel labelStaticIndEtat;
    private javax.swing.JLabel labelStaticIndNom;
    private javax.swing.JLabel labelStaticIndTpsPasse;
    private javax.swing.JTextArea textDescription;
    private javax.swing.JTextField textIndCharge;
    private javax.swing.JTextField textIndDateDebutPrevue;
    private javax.swing.JTextField textIndDateDebutReelle;
    private javax.swing.JTextField textIndDateFinPrevue;
    private javax.swing.JTextField textIndDateFinReelle;
    private javax.swing.JTextField textIndEtat;
    private javax.swing.JTextField textIndNom;
    private javax.swing.JTextField textIndRealisateur;
    private javax.swing.JTextField textIndTempsPasse;
    private javax.swing.JTextField textIndTempsRestant;
    // End of variables declaration//GEN-END:variables
    
}
