/*
 * JDialogGestionCDP.java
 *
 * Created on 5 mars 2005, 14:23
 */

package P2S.UI.View.JDialog;

import P2S.Control.Bundle.Bundle;
import P2S.Inf.ParserXMLCDP;
import P2S.UI.View.JFrameP2S;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URL;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import java.util.Vector;


/**
 *
 * @author  Guillaume
 */
public class JDialogGestionCDP extends javax.swing.JDialog {
    
    private HashMap mapCdp;
    private Vector listeProjetsLibres;
    private String fluxXml;
    
    /** Creates new form JDialogGestionCDP */
    public JDialogGestionCDP(java.awt.Frame parent, boolean modal, String flux) {
        super(parent, modal);
        fluxXml = flux;
        initComponents();
        initText();
        ParserXMLCDP parserCDP = new ParserXMLCDP(fluxXml);
        
        mapCdp = new HashMap();
        listeProjetsLibres = new Vector();
        parserCDP.lireChefProjet(mapCdp, listeProjetsLibres);
        
        Set lesCdp = mapCdp.keySet( ) ;
        Iterator it = lesCdp.iterator( ) ;
        while ( it . hasNext( ) ) {
            jComboBoxChoixCDP.addItem(it.next());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBoxChoixCDP = new javax.swing.JComboBox();
        jListProjetSupervise = new javax.swing.JList();
        jListProjetNonSupervise = new javax.swing.JList();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonAjouter = new javax.swing.JButton();
        jButtonConfirmer = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();
        jLabelResponsable = new javax.swing.JLabel();
        jLabelSansResponsable = new javax.swing.JLabel();
        jLabelCDP = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setResizable(false);
        jComboBoxChoixCDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxChoixCDPActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 307;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 20, 0, 0);
        getContentPane().add(jComboBoxChoixCDP, gridBagConstraints);

        jListProjetSupervise.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 255), null));
        jListProjetSupervise.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jListProjetSupervise.setAlignmentX(1.0F);
        jListProjetSupervise.setAlignmentY(10.0F);
        jListProjetSupervise.setMaximumSize(new java.awt.Dimension(10, 10));
        jListProjetSupervise.setMinimumSize(new java.awt.Dimension(10, 10));
        jListProjetSupervise.setName("");
        jListProjetSupervise.setPreferredSize(new java.awt.Dimension(10, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.ipady = 170;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 21, 0, 0);
        getContentPane().add(jListProjetSupervise, gridBagConstraints);

        jListProjetNonSupervise.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 153, 255), null));
        jListProjetNonSupervise.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11));
        jListProjetNonSupervise.setAlignmentX(1.0F);
        jListProjetNonSupervise.setAlignmentY(10.0F);
        jListProjetNonSupervise.setMaximumSize(new java.awt.Dimension(110, 110));
        jListProjetNonSupervise.setMinimumSize(new java.awt.Dimension(110, 110));
        jListProjetNonSupervise.setName("");
        jListProjetNonSupervise.setPreferredSize(new java.awt.Dimension(110, 110));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 0, 30);
        getContentPane().add(jListProjetNonSupervise, gridBagConstraints);

        jButtonSupprimer.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14));
        jButtonSupprimer.setText(">>");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(58, 10, 0, 0);
        getContentPane().add(jButtonSupprimer, gridBagConstraints);

        jButtonAjouter.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14));
        jButtonAjouter.setText("<<");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 10, 0, 0);
        getContentPane().add(jButtonAjouter, gridBagConstraints);

        jButtonConfirmer.setText("Ok");
        jButtonConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmerActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 91, 40, 0);
        getContentPane().add(jButtonConfirmer, gridBagConstraints);

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 40, 0);
        getContentPane().add(jButtonAnnuler, gridBagConstraints);

        jLabelResponsable.setText("Responsable des projets");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 20, 0, 0);
        getContentPane().add(jLabelResponsable, gridBagConstraints);

        jLabelSansResponsable.setText("Projets sans responsable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 9, 0, 0);
        getContentPane().add(jLabelSansResponsable, gridBagConstraints);

        jLabelCDP.setText("Chefs de projet");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 259;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        getContentPane().add(jLabelCDP, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-386)/2, (screenSize.height-399)/2, 386, 399);
    }//GEN-END:initComponents
    
    private void jButtonConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmerActionPerformed
        
        String flux = "";
        
        String nomCdp;
        String nomProjet;
        Vector listeProjets;
        String loginUtilisateur = ((JFrameP2S)this.getParent()).utilisateur.getLogin();
        
        Set lesCdp = mapCdp.keySet( ) ;
        Iterator it = lesCdp.iterator( ) ;
        flux += "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><assignationCDP>";
        while ( it . hasNext( ) ) {
            flux += "<CDP><nom>";
            nomCdp = (String)it.next();
            flux += nomCdp+"</nom>";
            listeProjets = (Vector) mapCdp.get(nomCdp);
            flux += "<projets>";
            for (int i=0;i<listeProjets.size();i++){
                nomProjet = (String)listeProjets.get(i);
                //URL url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDCDP?login="+loginUtilisateur+"&cdp="+nomCdp+"&projet=" + nomProjet);
            
                flux += "<projet>"+nomProjet+"</projet>";
            }
            flux += "</projets></CDP>";
            
        }
        flux += "</assignationCDP>";
        
       
        int fluxMax = 50;
        int longueurFlux = flux.length();
        int longueurActuelle = 0 ;
        URL url;        
        try{
            // On indique qu'on va lire un nouveau fichier pour que la servlet vide son buffer de reception
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDCDP?login="+loginUtilisateur+"&lecture=0&flux");
            
            BufferedReader in=new BufferedReader(new InputStreamReader(url.openStream()));
            // On lit le fichier
            
            int longueurReelle ;
            while(longueurActuelle < longueurFlux){
                if (longueurFlux-longueurActuelle>fluxMax) longueurReelle = fluxMax;
                else longueurReelle = longueurFlux-longueurActuelle;
                url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDCDP?login="+loginUtilisateur+"&lecture=1&flux="+flux.substring(longueurActuelle,longueurActuelle+longueurReelle).replaceAll("\\s","%20"));
                in = new BufferedReader(new InputStreamReader(url.openStream()));
                longueurActuelle += fluxMax;
            }
            
            // On indique qu'on a fini de lire le fichier
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDCDP?login="+loginUtilisateur+"&lecture=2&flux=");
            in = new BufferedReader(new InputStreamReader(url.openStream()));
            
            String reponse = new String("");
            String inputLine;
            while ((inputLine = in.readLine()) != null)
                reponse += inputLine;
            
            if(reponse.compareTo("1") == 0) {
                javax.swing.JOptionPane.showMessageDialog(null, Bundle.getText("ErrorValeurNulle"), Bundle.getText("ExceptionErrorTitle"), javax.swing.JOptionPane.ERROR_MESSAGE) ;
            }
            
        }catch(IOException e){
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(null, Bundle.getText("ErrorConnexionServer"), Bundle.getText("ExceptionErrorTitle"), javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        System.out.println(flux);
        this.dispose();
        
    }//GEN-LAST:event_jButtonConfirmerActionPerformed
    
    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonAnnulerActionPerformed
    
    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        //ajoute un projet a un chef de projet
        String nouveauProjet = (String) jListProjetNonSupervise.getSelectedValue();
        listeProjetsLibres.remove(nouveauProjet);
        String cdp = (String)jComboBoxChoixCDP.getSelectedItem();
        Vector listeProjetActuel = (Vector)mapCdp.get(cdp);
        listeProjetActuel.add(nouveauProjet);
        mapCdp.put(cdp,listeProjetActuel);
        reactualiseListeProjet();
    }//GEN-LAST:event_jButtonAjouterActionPerformed
    
    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        //retire un projet a un chef de projet
        
        String ancienProjet = (String) jListProjetSupervise.getSelectedValue();
        String cdp = (String)jComboBoxChoixCDP.getSelectedItem();
        Vector listeProjetActuel = (Vector)mapCdp.get(cdp);
        listeProjetActuel.remove(ancienProjet);
        listeProjetsLibres.add(ancienProjet);
        reactualiseListeProjet();
        
    }//GEN-LAST:event_jButtonSupprimerActionPerformed
    
    private void jComboBoxChoixCDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxChoixCDPActionPerformed
        //réaffichage des deux listes...
        reactualiseListeProjet();
    }//GEN-LAST:event_jComboBoxChoixCDPActionPerformed
    
    private void reactualiseListeProjet(){
        jListProjetNonSupervise.setListData(listeProjetsLibres);
        jListProjetSupervise.setListData((Vector)mapCdp.get((String)jComboBoxChoixCDP.getSelectedItem()));
    }
    
    private void initText(){
        this.jButtonConfirmer.setText(Bundle.getText("JDialogPreferences_JButton_Ok"));
        this.jButtonAnnuler.setText(Bundle.getText("JDialogPreferences_JButton_Annuler"));
        this.jLabelResponsable.setText(Bundle.getText("JDialogGestionCDP_JLabel_Responsable"));
        this.jLabelSansResponsable.setText(Bundle.getText("JDialogGestionCDP_JLabel_SansResponsable"));
        this.jLabelCDP.setText(Bundle.getText("JDialogGestionCDP_JLabel_CDP"));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonConfirmer;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox jComboBoxChoixCDP;
    private javax.swing.JLabel jLabelCDP;
    private javax.swing.JLabel jLabelResponsable;
    private javax.swing.JLabel jLabelSansResponsable;
    private javax.swing.JList jListProjetNonSupervise;
    private javax.swing.JList jListProjetSupervise;
    // End of variables declaration//GEN-END:variables
    
}
