package P2S.UI.View.JDialog;

import P2S.Control.Bundle.*;
import P2S.Model.*;
import P2S.UI.View.*;
import java.text.DateFormat;
import java.util.Locale;

/**
 *
 * @author  kassem
 */
public class JDialogMail extends javax.swing.JDialog {
    
    public JDialogMail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        this.initText();
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        labelDestinataire = new javax.swing.JLabel();
        textIndDestinataire = new javax.swing.JTextField();
        textMessage = new javax.swing.JTextArea();
        labelObjet = new javax.swing.JLabel();
        textIndObjet = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        labelDestinataire.setText("label");
        getContentPane().add(labelDestinataire, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, -1));

        textIndDestinataire.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndDestinataire, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 360, -1));

        textMessage.setLineWrap(true);
        textMessage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 360, 230));

        labelObjet.setText("label");
        getContentPane().add(labelObjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 50, -1));

        textIndObjet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndObjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 360, -1));

        buttonOK.setText("Envoyer");
        getContentPane().add(buttonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        buttonCancel.setText("Annuler");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        getContentPane().add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-494)/2, (screenSize.height-400)/2, 494, 400);
    }//GEN-END:initComponents

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    public void initText()
    {
           this.setTitle(Bundle.getText("JDialogMailTitle"));
           labelDestinataire.setText(Bundle.getText("JDialogMailTo"));
           labelObjet.setText(Bundle.getText("JDialogMailObject"));
           buttonOK.setText(Bundle.getText("JDialogMailSend"));
           buttonCancel.setText(Bundle.getText("JDialogMailCancel"));
           
    }
    
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel labelDestinataire;
    private javax.swing.JLabel labelObjet;
    private javax.swing.JTextField textIndDestinataire;
    private javax.swing.JTextField textIndObjet;
    private javax.swing.JTextArea textMessage;
    // End of variables declaration//GEN-END:variables
    
}
