package P2S.UI.View.JDialog;

import P2S.Control.Bundle.*;
import P2S.Control.*;
import P2S.Inf.ParserXMLPreferences;
import java.util.*;

/**
 * Boite de dialogue contenant les preferences du logiciel
 * @author Fabien Bouyssou
 */
public class JDialogPreferences extends javax.swing.JDialog {
    
    /**
     * Cree une nouvelle instance
     * @param parent Frame Parent
     * @param modal Modal
     */
    public JDialogPreferences(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // initialise le texte
        initTexte();
        
        /*P2S.P2S.ControllerLocale.addLocaleListener(new LocaleListener(){
            public void localeChanged() {
                initTexte();
            } 
        });*/
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        LabelLangue = new javax.swing.JLabel();
        ComboBoxLangue = new javax.swing.JComboBox();
        LabelHost = new javax.swing.JLabel();
        TextFieldHost = new javax.swing.JTextField();
        ButtonCancel = new javax.swing.JButton();
        ButtonOK = new javax.swing.JButton();
        LabelConnexionServeur = new javax.swing.JLabel();
        LabelPort = new javax.swing.JLabel();
        TextFieldPort = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        LabelLangue.setText("Langue");
        getContentPane().add(LabelLangue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        ComboBoxLangue.setModel(new javax.swing.DefaultComboBoxModel(new String[] { Bundle.getText("JDialogPreferences_ComboBoxLangue_Francais"), Bundle.getText("JDialogPreferences_ComboBoxLangue_Anglais") }));
        getContentPane().add(ComboBoxLangue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 130, -1));

        LabelHost.setText("Host");
        getContentPane().add(LabelHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        getContentPane().add(TextFieldHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 140, -1));

        ButtonCancel.setText("Annuler");
        ButtonCancel.setMaximumSize(new java.awt.Dimension(100, 23));
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        getContentPane().add(ButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 70, -1));

        ButtonOK.setText("OK");
        ButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOKActionPerformed(evt);
            }
        });

        getContentPane().add(ButtonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 50, -1));

        LabelConnexionServeur.setText("Connexion au serveur");
        getContentPane().add(LabelConnexionServeur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        LabelPort.setText("Port");
        getContentPane().add(LabelPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        getContentPane().add(TextFieldPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 140, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-289)/2, (screenSize.height-227)/2, 289, 227);
    }//GEN-END:initComponents

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void ButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonOKActionPerformed
        
        // On regarde la langue choisie et on change la Locale
        if(this.ComboBoxLangue.getSelectedItem().toString().compareTo(Bundle.getText("JDialogPreferences_ComboBoxLangue_Francais")) == 0)
        {
            Bundle.setCurrentLocale(Locale.FRENCH);
            P2S.P2S.ControllerLocale.fireLocaleChanged(); // genere un evenement changement de langue
            P2S.P2S.Preferences.setProperty("langue", "fr");
        }
        else if(this.ComboBoxLangue.getSelectedItem().toString().compareTo(Bundle.getText("JDialogPreferences_ComboBoxLangue_Anglais")) == 0)
        {
            Bundle.setCurrentLocale(Locale.ENGLISH);
            P2S.P2S.ControllerLocale.fireLocaleChanged(); // genere un evenement changement de langue
            P2S.P2S.Preferences.setProperty("langue", "en");
        }
        // On sauve l'adresse du serveur et le port utilisé
        System.out.println(this.TextFieldPort.getText());
        P2S.P2S.Preferences.setProperty("host", this.TextFieldHost.getText());
        P2S.P2S.Preferences.setProperty("port", this.TextFieldPort.getText());
        
        // On sauve les preferences dans le ficher
        P2S.P2S.saveProperties();
        this.dispose();
    }//GEN-LAST:event_ButtonOKActionPerformed

    private void initTexte()
    {
        this.setTitle(Bundle.getText("JDialogPreferences_TitreFenetre"));
                
        LabelLangue.setText(Bundle.getText("JDialogPreferences_JLabel_Langue"));
        
        if(Locale.getDefault().toString().compareTo("fr") == 0)
            this.ComboBoxLangue.setSelectedItem(Bundle.getText("JDialogPreferences_ComboBoxLangue_Francais"));
        else if(Locale.getDefault().toString().compareTo("en") == 0)
            this.ComboBoxLangue.setSelectedItem(Bundle.getText("JDialogPreferences_ComboBoxLangue_Anglais"));
        
        this.LabelConnexionServeur.setText(Bundle.getText("JDialogPreferences_JLabel_ConnexionServeur"));
        this.LabelHost.setText(Bundle.getText("JDialogPreferences_JLabel_Host"));
        this.LabelPort.setText(Bundle.getText("JDialogPreferences_JLabel_Port"));
        this.ButtonOK.setText(Bundle.getText("JDialogPreferences_JButton_Ok"));
        this.ButtonCancel.setText(Bundle.getText("JDialogPreferences_JButton_Annuler"));
                
        
        this.TextFieldHost.setText(P2S.P2S.Preferences.getProperty("host"));
        this.TextFieldPort.setText(P2S.P2S.Preferences.getProperty("port"));
    }
        
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonOK;
    private javax.swing.JComboBox ComboBoxLangue;
    private javax.swing.JLabel LabelConnexionServeur;
    private javax.swing.JLabel LabelHost;
    private javax.swing.JLabel LabelLangue;
    private javax.swing.JLabel LabelPort;
    private javax.swing.JTextField TextFieldHost;
    private javax.swing.JTextField TextFieldPort;
    // End of variables declaration//GEN-END:variables
    
}
