/*
 * JDialogAjouterProjet.java
 *
 * Created on 11 février 2005, 00:47
 */

package P2S.UI.View.JDialog;

import P2S.Control.Bundle.Bundle;
import P2S.Inf.ParserXMLPreferences;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import P2S.UI.View.*;

/**
 *
 * @author  Fabien
 */
public class JDialogAjouterProjet extends javax.swing.JDialog {
    
    /** Creates new form JDialogAjouterProjet */
    public JDialogAjouterProjet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        initTexte();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabelStaticURLProjet = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldURL = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabelStaticURLProjet.setText("URL du fichier Projet : ");
        getContentPane().add(jLabelStaticURLProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jButtonOK.setText("jButton1");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        getContentPane().add(jButtonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jButtonCancel.setText("jButton2");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        getContentPane().add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        getContentPane().add(jTextFieldURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 200, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-345)/2, (screenSize.height-195)/2, 345, 195);
    }//GEN-END:initComponents
    
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed
    
    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        String URLFichier = this.jTextFieldURL.getText();
        
        try{
            ParserXMLPreferences parserPref = new ParserXMLPreferences(P2S.P2S.readFile("P2S/preferences.xml"));
            URL url = new URL("http://"+parserPref.lireAdresseServeur()+":"+parserPref.lirePortServeur()+"/p2sserver/MAJBDServlet?login="+((JFrameP2S)this.getParent()).utilisateur.getLogin()+"&url="+URLFichier);
            
            // Buffer qui va recuperer la reponse de la servlet
            BufferedReader in = new BufferedReader(
                    new InputStreamReader(
                    url.openStream()));
            
            //Recuperation de la reponse envoye par la Servlet
            /*String reponse = new String("");
            String inputLine;
            while ((inputLine = in.readLine()) != null)
                reponse += inputLine;
            
            if(reponse.compareTo("erreur") == 0) {
                System.out.println("Probleme lors de l'ajout du projet dans la BD");
            }*/
            in.close();
        } catch(MalformedURLException e1){
            e1.printStackTrace();
        } catch(IOException e2){
            e2.printStackTrace();
        }
        
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed
    
    private void initTexte(){
        this.setTitle(Bundle.getText("JDialogAjouterProjet_TitreFenetre"));
        
        this.jButtonOK.setText(Bundle.getText("JDialogAjouterProjet_ButtonOK"));
        this.jButtonCancel.setText(Bundle.getText("JDialogAjouterProjet_ButtonCancel"));
        this.jLabelStaticURLProjet.setText(Bundle.getText("JDialogAjouterProjet_LabelStaticURLFichier"));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelStaticURLProjet;
    private javax.swing.JTextField jTextFieldURL;
    // End of variables declaration//GEN-END:variables
    
}
