package P2S.UI.View.JDialog;

import P2S.UI.View.*;
import P2S.Model.*;
import P2S.Control.Bundle.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;

/**
 * jdialog permettant de creer un projet pour le superviseur courant
 * @author Fabien
 */
public class JDialogCreerProjet extends javax.swing.JDialog {
        
    private Vector listeMesures;
    private String[] titreColonnes;
    
    /**
     * Creates new form JDialogCreerProjet
     * @param parent frame parent de la jdialog
     * @param modal indique si la jdialog est modal ou pas
     */
    public JDialogCreerProjet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        listeMesures = new Vector();
        
        // Initialisation de la table des mesures
        Object donnees[][] = new Object[0][0];
        titreColonnes = new String[3];
        titreColonnes[0] = Bundle.getText("JDialogCreerProjet_JTable_NomCol1");
        titreColonnes[1] = Bundle.getText("JDialogCreerProjet_JTable_NomCol2");
        titreColonnes[2] = Bundle.getText("JDialogCreerProjet_JTable_NomCol3");
                             
        this.jTableMesures.setModel(new ModeleTableMesure(donnees,titreColonnes));
        
        // Initialisation du texte des labels
        this.initText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        JLabelNom = new javax.swing.JLabel();
        JLabelDateDebut = new javax.swing.JLabel();
        JTextFieldDateDebutJour = new javax.swing.JTextField();
        JLabelDateFin = new javax.swing.JLabel();
        JTextFieldDateFinMois = new javax.swing.JTextField();
        JLabelMesures = new javax.swing.JLabel();
        JScrollPaneMesures = new javax.swing.JScrollPane();
        jTableMesures = new javax.swing.JTable();
        JButtonOk = new javax.swing.JButton();
        JButtonAnnuler = new javax.swing.JButton();
        JButtonAjouterMesure = new javax.swing.JButton();
        JTextFieldNom = new javax.swing.JTextField();
        JTextFieldDateDebutMois = new javax.swing.JTextField();
        JTextFieldDateDebutAnnee = new javax.swing.JTextField();
        JTextFieldDateFinAnnee = new javax.swing.JTextField();
        JTextFieldDateFinJour = new javax.swing.JTextField();
        JLabelDescription = new javax.swing.JLabel();
        JTextAreaDescription = new javax.swing.JTextArea();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        JLabelNom.setText("Nom du projet :");
        getContentPane().add(JLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        JLabelDateDebut.setText("Date de d\u00e9but :");
        getContentPane().add(JLabelDateDebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        JTextFieldDateDebutJour.setText("jj");
        getContentPane().add(JTextFieldDateDebutJour, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 30, -1));

        JLabelDateFin.setText("Date de fin :");
        getContentPane().add(JLabelDateFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        JTextFieldDateFinMois.setText("mm");
        getContentPane().add(JTextFieldDateFinMois, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 30, -1));

        JLabelMesures.setText("Mesures :");
        getContentPane().add(JLabelMesures, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        JScrollPaneMesures.setBackground(new java.awt.Color(255, 255, 255));
        JScrollPaneMesures.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jTableMesures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JScrollPaneMesures.setViewportView(jTableMesures);

        getContentPane().add(JScrollPaneMesures, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 400, 110));

        JButtonOk.setText("OK");
        JButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonOkActionPerformed(evt);
            }
        });

        getContentPane().add(JButtonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        JButtonAnnuler.setText("Annuler");
        JButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAnnulerActionPerformed(evt);
            }
        });

        getContentPane().add(JButtonAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, -1, -1));

        JButtonAjouterMesure.setText("Ajouter mesure");
        JButtonAjouterMesure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAjouterMesureActionPerformed(evt);
            }
        });

        getContentPane().add(JButtonAjouterMesure, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 110, -1));

        getContentPane().add(JTextFieldNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        JTextFieldDateDebutMois.setText("mm");
        getContentPane().add(JTextFieldDateDebutMois, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 30, -1));

        JTextFieldDateDebutAnnee.setText("aaaa");
        getContentPane().add(JTextFieldDateDebutAnnee, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 40, -1));

        JTextFieldDateFinAnnee.setText("aaaa");
        getContentPane().add(JTextFieldDateFinAnnee, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 40, -1));

        JTextFieldDateFinJour.setText("jj");
        getContentPane().add(JTextFieldDateFinJour, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 30, -1));

        JLabelDescription.setText("Description : ");
        getContentPane().add(JLabelDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        getContentPane().add(JTextAreaDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 380, 80));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-514)/2, (screenSize.height-425)/2, 514, 425);
    }//GEN-END:initComponents

    private void initText()
    {
        this.setTitle(Bundle.getText("JDialogCreerProjet_TitreFenetre"));
        
        JLabelNom.setText(Bundle.getText("JDialogCreerProjet_JLabel_Nom"));
        JLabelDateDebut.setText(Bundle.getText("JDialogCreerProjet_JLabel_DateDebut"));
        JLabelDateFin.setText(Bundle.getText("JDialogCreerProjet_JLabel_DateFin"));
        JLabelDescription.setText(Bundle.getText("JDialogCreerProjet_JLabel_Description"));
        JLabelMesures.setText(Bundle.getText("JDialogCreerProjet_JLabel_Mesures"));
        JButtonOk.setText(Bundle.getText("JDialogCreerProjet_JButton_Ok"));
        JButtonAnnuler.setText(Bundle.getText("JDialogCreerProjet_JButton_Annuler"));
        JButtonAjouterMesure.setText(Bundle.getText("JDialogCreerProjet_JButton_AjouterMesure"));
        JTextFieldDateDebutJour.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateDebutJour"));
        JTextFieldDateDebutMois.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateDebutMois"));
        JTextFieldDateDebutAnnee.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateDebutAnnee"));
        JTextFieldDateFinJour.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateFinJour"));
        JTextFieldDateFinMois.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateFinMois"));
        JTextFieldDateFinAnnee.setText(Bundle.getText("JDialogCreerProjet_JTextField_DateFinAnnee"));
    }
    
    private void JButtonAjouterMesureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAjouterMesureActionPerformed
        new JDialogAjoutMesure((JFrameP2S)(this.getParent()),true).show();       
    }//GEN-LAST:event_JButtonAjouterMesureActionPerformed

    private void JButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_JButtonAnnulerActionPerformed

    private void JButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonOkActionPerformed
        if(this.JTextFieldNom.getText().compareTo("") != 0){
            // format de la date
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            
            // On recupere la date debut
            Date dateDebut = null;
            try{                        
                dateDebut = dateFormat.parse(this.JTextFieldDateDebutAnnee.getText()+"-"+this.JTextFieldDateDebutMois.getText()+"-"+this.JTextFieldDateDebutJour.getText());
            } catch(ParseException e1){
                System.out.println("Probleme pour parser dateDebut");
            }
            
            // On recupere la date fin
            Date dateFin = null;
            try{                        
                dateFin = dateFormat.parse(this.JTextFieldDateFinAnnee.getText()+"-"+this.JTextFieldDateFinMois.getText()+"-"+this.JTextFieldDateFinJour.getText());
            } catch(ParseException e1){
                System.out.println("Probleme pour parser dateFin");
            }
            
            // On ajoute le projet
            ((JFrameP2S)this.getParent()).ajouterProjet(new Projet(this.JTextFieldNom.getText(),this.JTextAreaDescription.getText(),dateDebut,dateFin,this.listeMesures));
            this.dispose();
        }
        else // Un nom de projet n'a pas ?tait entre
            JOptionPane.showMessageDialog(this, new String("Veuillez entrer un nom de projet"),new String("Probl?me Cr?ation Projet") , JOptionPane.WARNING_MESSAGE);
        
        
    }//GEN-LAST:event_JButtonOkActionPerformed
    
    /**
     * permet d'ajouter une mesure au projet
     * @param mesure Mesure ? ajouter
     */
    public void ajouterMesure(Mesure mesure)
    {
        listeMesures.add(mesure);
    }
    
    /**
     * Rafraichit l'affichage des mesures
     */
    public void rafarichirMesures()
    {
        Object donnees[][] = new Object[listeMesures.size()][3];
        
        for(int i=0;i<listeMesures.size();i++)
        {
            donnees[i][0] = ((Mesure)(listeMesures.get(i))).get_nom();
            donnees[i][1] = new Integer(((Mesure)(listeMesures.get(i))).get_limiteInf());
            donnees[i][2] = new Integer(((Mesure)(listeMesures.get(i))).get_limiteSup());
        }
        this.jTableMesures.setModel(new ModeleTableMesure(donnees,titreColonnes));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAjouterMesure;
    private javax.swing.JButton JButtonAnnuler;
    private javax.swing.JButton JButtonOk;
    private javax.swing.JLabel JLabelDateDebut;
    private javax.swing.JLabel JLabelDateFin;
    private javax.swing.JLabel JLabelDescription;
    private javax.swing.JLabel JLabelMesures;
    private javax.swing.JLabel JLabelNom;
    private javax.swing.JScrollPane JScrollPaneMesures;
    private javax.swing.JTextArea JTextAreaDescription;
    private javax.swing.JTextField JTextFieldDateDebutAnnee;
    private javax.swing.JTextField JTextFieldDateDebutJour;
    private javax.swing.JTextField JTextFieldDateDebutMois;
    private javax.swing.JTextField JTextFieldDateFinAnnee;
    private javax.swing.JTextField JTextFieldDateFinJour;
    private javax.swing.JTextField JTextFieldDateFinMois;
    private javax.swing.JTextField JTextFieldNom;
    private javax.swing.JTable jTableMesures;
    // End of variables declaration//GEN-END:variables
    
}
