package P2S.UI.View.JDialog;

import P2S.Control.Bundle.*;
import P2S.Model.*;
import P2S.UI.View.*;
import java.text.DateFormat;
import java.util.Locale;

/**
 *
 * @author  kassem
 */
public class JDialogMail extends javax.swing.JDialog {
    
    /** Creates new form JDialogAjoutMesure */
    public JDialogMail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        this.initText();
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        labelDestinataire = new javax.swing.JLabel();
        textIndDestinataire = new javax.swing.JTextField();
        textMessage = new javax.swing.JTextArea();
        labelObjet = new javax.swing.JLabel();
        textIndObjet = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        labelDestinataire.setText("A :");
        getContentPane().add(labelDestinataire, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        textIndDestinataire.setBackground(new java.awt.Color(255, 255, 255));
        textIndDestinataire.setEditable(false);
        textIndDestinataire.setText("a");
        textIndDestinataire.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndDestinataire, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 170, -1));

        textMessage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 170, 90));

        labelObjet.setText("Objet  :");
        getContentPane().add(labelObjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, -1));

        textIndObjet.setBackground(new java.awt.Color(255, 255, 255));
        textIndObjet.setEditable(false);
        textIndObjet.setText("objet");
        textIndObjet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndObjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 170, -1));

        buttonOK.setText("Envoyer");
        getContentPane().add(buttonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        buttonCancel.setText("Annuler");
        getContentPane().add(buttonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-400)/2, 400, 400);
    }//GEN-END:initComponents

    public void initText()
    {
             
    }
    
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel labelDestinataire;
    private javax.swing.JLabel labelObjet;
    private javax.swing.JTextField textIndDestinataire;
    private javax.swing.JTextField textIndObjet;
    private javax.swing.JTextArea textMessage;
    // End of variables declaration//GEN-END:variables
    
}
