package P2S.UI.View.JDialog;

import P2S.Control.Bundle.*;
import java.net.*;
import java.io.*;
import javax.swing.*;
import java.awt.Color;


/**
 *
 * @author  kassem
 */
public class JDialogLireMessages extends javax.swing.JDialog {
    private String message;
    private String sujet;
    
    public JDialogLireMessages(java.awt.Frame parent, boolean modal, String sujet, String message) {
        super(parent, modal);
        initComponents();
        this.sujet = sujet;
        this.message = message;
       
        this.initText();
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        textMessage = new javax.swing.JTextArea();
        labelObjet = new javax.swing.JLabel();
        textIndObjet = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        textMessage.setEditable(false);
        textMessage.setLineWrap(true);
        textMessage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 360, 230));

        labelObjet.setText("label");
        getContentPane().add(labelObjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, -1));

        textIndObjet.setEditable(false);
        textIndObjet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(textIndObjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 360, -1));

        buttonOK.setText("jButton1");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        getContentPane().add(buttonOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-494)/2, (screenSize.height-400)/2, 494, 400);
    }//GEN-END:initComponents
 
 

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

   
   
    public void initText()
    {
           this.setTitle(Bundle.getText("JDialogAlerteTitle"));
           labelObjet.setText(Bundle.getText("JDialogAlerteObject"));
           buttonOK.setText(Bundle.getText("JDialogAlerteSend"));
           textIndObjet.setBackground(new Color(255,255,255));
           textIndObjet.setText(sujet);
           textMessage.setText(message);
    }
    
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel labelObjet;
    private javax.swing.JTextField textIndObjet;
    private javax.swing.JTextArea textMessage;
    // End of variables declaration//GEN-END:variables
    
}
