/*
 * JPanelIndicTachesMembre.java
 *
 * Created on 26 février 2005, 10:57
 */

package P2S.UI.View.JPanel;

import P2S.Control.Bundle.Bundle;
import P2S.Model.IndicateursTacheMembre;
import P2S.UI.View.JDialog.ModeleTableMesure;
import java.util.Vector;

/**
 *
 * @author  Conde Mike K
 */
public class JPanelIndicTachesMembre extends javax.swing.JPanel {
    
    private String[] nomsColonnes = {Bundle.getText("JTableIndicTachesColonne1"), Bundle.getText("JTableIndicTachesColonne2")} ;
    private Object[][] donnees = null ;
    
    /** Creates new form JPanelIndicTachesMembre */
    public JPanelIndicTachesMembre (Vector indicateursTache) {
        
        // initialisation des donnees
        donnees = new Object[indicateursTache.size()][2] ;
        for (int i = 0 ; i < donnees.length ; i++)
        {
            if (indicateursTache.get(i) instanceof IndicateursTacheMembre)
            {
                donnees[i][0] = ((IndicateursTacheMembre)indicateursTache.get(i)).getNom() ;
                donnees[i][1] = ((IndicateursTacheMembre)indicateursTache.get(i)).getTempsPasse() ;
            }
        }
        
        ModeleTableMesure tableModel = new ModeleTableMesure(donnees, nomsColonnes) ;
        
        initComponents ();
        table.setModel(tableModel) ;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        tableScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tableScrollPane.setPreferredSize(new java.awt.Dimension(100, 64));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        table.setPreferredSize(new java.awt.Dimension(100, 64));
        tableScrollPane.setViewportView(table);

        add(tableScrollPane, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    // End of variables declaration//GEN-END:variables
    
        
}
