/*
 * JPanelInfoRisque.java
 *
 * Created on 23 février 2005, 19:08
 */

package P2S.UI.View.JPanel;


import P2S.Control.Bundle.Bundle;
import P2S.Model.Risque;
import P2S.UI.View.JDialog.ModeleTableMesure;
import java.awt.Component;
import java.util.Vector ;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableCellRenderer;


/**
 *
 * @author  Conde Mike K
 */
public class JPanelInfoRisque extends javax.swing.JPanel {
    
    private String[] titresColonnes = {Bundle.getText("JTableRisquesColonne1"),
                Bundle.getText("JTableRisquesColonne2"),
                Bundle.getText("JTableRisquesColonne3"),
                Bundle.getText("JTableRisquesColonne4"),
                Bundle.getText("JTableRisquesColonne5")} ; ;
    private Object[][] donnees = null ;
    
    /** Creates new form JPanelInfoRisque */
    public JPanelInfoRisque (Vector risques) {
        
        donnees = new Object[risques.size()][5] ;
        for (int i = 0 ; i < donnees.length ; i++)
        {
            if (risques.get(i) instanceof Risque)
            {
                donnees[i][0] = ((Risque)risques.get(i)).getNom() ;
                donnees[i][1] = ((Risque)risques.get(i)).getDescription() ;
                donnees[i][2] = ((Risque)risques.get(i)).getPriorite() ;
                donnees[i][3] = ((Risque)risques.get(i)).getImpact() ;
                donnees[i][4] = ((Risque)risques.get(i)).getEtat() ;
            }
        }
        
        ModeleTableMesure tableModel = new ModeleTableMesure(donnees, titresColonnes) ;
        
        initComponents ();     
        
        table.setModel(tableModel) ;     
        

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    
       
}
