/*
 * JPanelIndicArtefactsMembre.java
 *
 * Created on 26 février 2005, 22:29
 */

package P2S.UI.View.JPanel;

import P2S.Control.Bundle.Bundle;
import P2S.Model.IndicateursProduitMembre;
import P2S.UI.View.JDialog.ModeleTableMesure;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.JTable;


/**
 *
 * @author  Conde Mike K
 */
public class JPanelIndicArtefactsMembre extends javax.swing.JPanel {
    
    
    private String[] nomsColonnes = {Bundle.getText("JTableArtefactsColonne1"),
                Bundle.getText("JTableIndicArtefactsColonne2")} ;
    private Object[][] donnees = null ;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    
    /** Creates new form JPanelArtefactsMembre */
    public JPanelIndicArtefactsMembre (Vector artefacts) {
        initComponents ();
        
        donnees = new Object[artefacts.size()][2] ;
        for (int i = 0 ; i < donnees.length ; i++)
        {
            if (artefacts.get(i) instanceof IndicateursProduitMembre)
            {
                donnees[i][0] = ((IndicateursProduitMembre)artefacts.get(i)).getNom() ;
                donnees[i][1] = ((IndicateursProduitMembre)artefacts.get(i)).getEtat() ;
            }
        }
        
        ModeleTableMesure tableModel = new ModeleTableMesure(donnees, nomsColonnes) ;        
        table = new JTable(tableModel) ;
        tableScrollPane = new JScrollPane(table) ;
        add(tableScrollPane, java.awt.BorderLayout.CENTER);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
