/*
 * JPanelInfoRisque.java
 *
 * Created on 23 février 2005, 19:08
 */

package P2S.UI.View.JPanel;


import P2S.Control.Bundle.Bundle;
import P2S.Model.IndicateursProjet;
import P2S.Model.Iteration;
import P2S.Model.Projet;
import P2S.Model.Risque;
import java.text.DateFormat;
import java.util.Locale;
import java.util.Vector ;
import javax.swing.table.DefaultTableModel ;

/**
 *
 * @author  Conde Mike K
 */
public class JPanelInfoRisque extends javax.swing.JPanel {
    
    private Vector risques ;
    
    /** Creates new form JPanelInfoRisque */
    public JPanelInfoRisque (Projet proj) {
        initComponents ();
        
        risques = proj.getListeRisques() ;
        
        // remplissage de la JTable        
        // titres des colonnes
        Vector titresColonnes = new Vector() ;
        titresColonnes.add(Bundle.getText("JTableRisquesColonne1")) ;
        titresColonnes.add(Bundle.getText("JTableRisquesColonne2")) ;
        titresColonnes.add(Bundle.getText("JTableRisquesColonne3")) ;
        titresColonnes.add(Bundle.getText("JTableRisquesColonne4")) ;
        titresColonnes.add(Bundle.getText("JTableRisquesColonne5")) ;
        
        // changement de taille de certaines colonnes       
        
        
        ((DefaultTableModel)(jTable1.getModel())).setColumnIdentifiers(titresColonnes) ;
        
       for (int i = 0 ; i < risques.size() ; i++)
        {
            Risque tempRisque ;
            Vector donneesRisque ;   // les donnees les plus importantes
            if (risques.get(i) instanceof Risque) // precaution on teste si l'objet est une Tisque
            {
                // affichage des informations sommaires des tisques
                tempRisque = (Risque)risques.get(i) ;
                donneesRisque = new Vector() ;
                donneesRisque.add(tempRisque.getNom()) ;
                donneesRisque.add(tempRisque.getDescription()) ;
                donneesRisque.add(Integer.toString(tempRisque.getPriorite())) ;
                donneesRisque.add(Integer.toString(tempRisque.getImpact())) ;
                donneesRisque.add(Integer.toString(tempRisque.getEtat())) ;                                
                ((DefaultTableModel)(jTable1.getModel())).addRow (donneesRisque) ;
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
