/*
 * JPanelInfoTaches.java
 *
 * Created on 23 février 2005, 10:41
 */

package P2S.UI.View.JPanel;


import java.util.Vector ;
import P2S.Model.Tache; 
import P2S.Model.Mesure; 

/** represente la liste des taches passes dans le constructeur
 *
 * @author  Conde Mike K
 */
public class JPanelInfoTaches extends javax.swing.JPanel {
    
    /** Creates new form JPanelInfoTaches */
    public JPanelInfoTaches (Vector taches) {
        initComponents ();
        
        for (int i = 0 ; i < taches.size() ; i++)
        {
            if (taches.get(i) instanceof Mesure) // precaution on teste si l'objet est une Tache
            {
                // affichage des informations sommaires des taches
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents () {//GEN-BEGIN:initComponents
        
        setLayout (new java.awt.BorderLayout ());
        
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
