/*
 * JPanelInfoTaches.java
 *
 * Created on 23 février 2005, 10:41
 */

package P2S.UI.View.JPanel;


import java.util.Vector ;
import P2S.Model.Tache; 
import P2S.Model.Mesure; 
import javax.swing.* ;

/** represente la liste des taches passes dans le constructeur
 *
 * @author  Conde Mike K
 */
public class JPanelInfoTaches extends javax.swing.JPanel {
    
    private JLabel nomTache ;
    private JButton boutonDetails ;
    
    /** Creates new form JPanelInfoTaches */
    public JPanelInfoTaches (Vector taches) {
        initComponents ();
        
        // ATTENTION : le code qui suit n'est pas genere car le nombre de taches n'est pas connu a l'avance
        // les variables declarees sont reutilisees
        
        
        for (int i = 0 ; i < taches.size() ; i++)
        {
            Tache tempTache ;
            if (taches.get(i) instanceof Tache) // precaution on teste si l'objet est une Tache
            {
                // affichage des informations sommaires des taches
                tempTache = (Tache)taches.get(i) ;
                nomTache = new JLabel(tempTache.getNom()) ;
                //nomTache.setText(tempTache.getNom());
                add(nomTache, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, (i + 1) * 20, 70, -1));
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
