/*
 * JPanelInfoSeuil.java
 *
 * Created on 21 mars 2005, 15:46
 */

package P2S.UI.View.JPanel;

import P2S.Control.Bundle.Bundle;
import P2S.Model.Projet;
import P2S.Model.SeuilsFixes;
import P2S.UI.View.JFrameP2S;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

/**
 *
 * @author  Guillaume
 */
public class JPanelInfoSeuil extends javax.swing.JPanel {
    
    private Projet projet;
    private String ancienneValeur;
    private String ancienneValeur2;
    
    /** Creates new form JPanelInfoSeuil */
    public JPanelInfoSeuil(Projet proj) {
        projet = proj;
        initComponents();
        initText();
        initSeuil();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        indicateursGeneraux = new javax.swing.JLabel();
        seuilMin = new javax.swing.JLabel();
        seuilMax = new javax.swing.JLabel();
        totalChargesProjet = new javax.swing.JLabel();
        totalChargesProjetSeuilMin = new javax.swing.JTextField();
        totalChargesProjetSeuilMax = new javax.swing.JTextField();
        tacheTermineesProjet = new javax.swing.JLabel();
        tacheTermineesProjetSeuilMin = new javax.swing.JTextField();
        tacheTermineesProjetSeuilMax = new javax.swing.JTextField();
        dureeMoyenneProjet = new javax.swing.JLabel();
        dureeMoyenneProjetSeuilMin = new javax.swing.JTextField();
        dureeMoyenneProjetSeuilMax = new javax.swing.JTextField();
        nombreParticipantProjet = new javax.swing.JLabel();
        nombreParticipantProjetSeuilMin = new javax.swing.JTextField();
        nombreParticipantProjetSeuilMax = new javax.swing.JTextField();
        indicateursIterations = new javax.swing.JLabel();
        totalChargesIteration = new javax.swing.JLabel();
        totalChargesIterationSeuilMin = new javax.swing.JTextField();
        totalChargesIterationSeuilMax = new javax.swing.JTextField();
        tacheTermineesIteration = new javax.swing.JLabel();
        tacheTermineesIterationSeuilMin = new javax.swing.JTextField();
        tacheTermineesIterationSeuilMax = new javax.swing.JTextField();
        dureeMoyenneIteration = new javax.swing.JLabel();
        dureeMoyenneIterationSeuilMin = new javax.swing.JTextField();
        dureeMoyenneIterationSeuilMax = new javax.swing.JTextField();
        nombreParticipantIteration = new javax.swing.JLabel();
        nombreParticipantIterationSeuilMin = new javax.swing.JTextField();
        nombreParticipantIterationSeuilMax = new javax.swing.JTextField();
        chargeMoyenne = new javax.swing.JLabel();
        chargeMoyenneSeuilMin = new javax.swing.JTextField();
        chargeMoyenneSeuilMax = new javax.swing.JTextField();
        nombreTacheParticipant = new javax.swing.JLabel();
        nombreTacheParticipantSeuilMin = new javax.swing.JTextField();
        nombreTacheParticipantSeuilMax = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indicateursGeneraux.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_titreGeneral"));
        add(indicateursGeneraux, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, -1));

        seuilMin.setText("Min");
        add(seuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 40, -1));

        seuilMax.setText("Max");
        add(seuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        add(totalChargesProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, -1));

        totalChargesProjetSeuilMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalChargesProjetSeuilMinFocusLost(evt);
            }
        });

        add(totalChargesProjetSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 40, -1));

        totalChargesProjetSeuilMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalChargesProjetSeuilMaxFocusLost(evt);
            }
        });

        add(totalChargesProjetSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 40, -1));

        tacheTermineesProjet.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_nbTachesTerminees"));
        add(tacheTermineesProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, -1));

        tacheTermineesProjetSeuilMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tacheTermineesProjetSeuilMinFocusLost(evt);
            }
        });

        add(tacheTermineesProjetSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 40, -1));

        tacheTermineesProjetSeuilMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tacheTermineesProjetSeuilMaxFocusLost(evt);
            }
        });

        add(tacheTermineesProjetSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 40, -1));

        dureeMoyenneProjet.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_duréeMoyenneTâches"));
        add(dureeMoyenneProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, -1));

        dureeMoyenneProjetSeuilMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dureeMoyenneProjetSeuilMinFocusLost(evt);
            }
        });

        add(dureeMoyenneProjetSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 40, -1));

        dureeMoyenneProjetSeuilMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dureeMoyenneProjetSeuilMaxFocusLost(evt);
            }
        });

        add(dureeMoyenneProjetSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 40, -1));

        nombreParticipantProjet.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_nbParticipantsTaches"));
        add(nombreParticipantProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, -1));

        nombreParticipantProjetSeuilMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreParticipantProjetSeuilMinFocusLost(evt);
            }
        });

        add(nombreParticipantProjetSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 40, -1));

        nombreParticipantProjetSeuilMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreParticipantProjetSeuilMaxFocusLost(evt);
            }
        });

        add(nombreParticipantProjetSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 40, -1));

        indicateursIterations.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_titreTaches"));
        add(indicateursIterations, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, -1));

        totalChargesIteration.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_totalChargesTaches"));
        add(totalChargesIteration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, -1));

        totalChargesIterationSeuilMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalChargesIterationSeuilMinFocusLost(evt);
            }
        });

        add(totalChargesIterationSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 40, -1));

        totalChargesIterationSeuilMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalChargesIterationSeuilMaxFocusLost(evt);
            }
        });

        add(totalChargesIterationSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 40, -1));

        tacheTermineesIteration.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_nbTachesTermineesTaches"));
        add(tacheTermineesIteration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 220, -1));

        tacheTermineesIterationSeuilMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tacheTermineesIterationSeuilMinFocusLost(evt);
            }
        });

        add(tacheTermineesIterationSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 40, -1));

        tacheTermineesIterationSeuilMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tacheTermineesIterationSeuilMaxFocusLost(evt);
            }
        });

        add(tacheTermineesIterationSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 40, -1));

        dureeMoyenneIteration.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_duréeMoyenneTâchesTaches"));
        add(dureeMoyenneIteration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, -1));

        dureeMoyenneIterationSeuilMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dureeMoyenneIterationSeuilMinFocusLost(evt);
            }
        });

        add(dureeMoyenneIterationSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 40, -1));

        dureeMoyenneIterationSeuilMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dureeMoyenneIterationSeuilMaxFocusLost(evt);
            }
        });

        add(dureeMoyenneIterationSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 40, -1));

        nombreParticipantIteration.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_nbParticipantsTaches"));
        add(nombreParticipantIteration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, -1));

        nombreParticipantIterationSeuilMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreParticipantIterationSeuilMinFocusLost(evt);
            }
        });

        add(nombreParticipantIterationSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 40, -1));

        nombreParticipantIterationSeuilMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreParticipantIterationSeuilMaxFocusLost(evt);
            }
        });

        add(nombreParticipantIterationSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 40, -1));

        chargeMoyenne.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_chargeMoyenneParticipants"));
        add(chargeMoyenne, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, -1));

        chargeMoyenneSeuilMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                chargeMoyenneSeuilMinFocusLost(evt);
            }
        });

        add(chargeMoyenneSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 40, -1));

        chargeMoyenneSeuilMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                chargeMoyenneSeuilMaxFocusLost(evt);
            }
        });

        add(chargeMoyenneSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 40, -1));

        nombreTacheParticipant.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_nbMoyenTaches"));
        add(nombreTacheParticipant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, -1));

        nombreTacheParticipantSeuilMin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTacheParticipantSeuilMinFocusLost(evt);
            }
        });

        add(nombreTacheParticipantSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 40, -1));

        nombreTacheParticipantSeuilMax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreTacheParticipantSeuilMaxFocusLost(evt);
            }
        });

        add(nombreTacheParticipantSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 40, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/P2S/Resources/save.gif")));
        jButton1.setText(java.util.ResourceBundle.getBundle("P2S/Control/Bundle/label_fr").getString("JPanelSeuils_bouton"));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{     
            String login = ((JFrameP2S)this.getTopLevelAncestor()).utilisateur.getLogin();
            String pass = ((JFrameP2S)this.getTopLevelAncestor()).utilisateur.getPassword();
            String nomProjet = projet.getNom().replaceAll("\\s","%20");
            
            SeuilsFixes seuilsFixes = projet.getSeuilFixes();
            
            // Envoie de tous les jtextfields qui seront insérés dans la servlet
            
            
            
            
              
            
            URL url;
            
            if(Integer.parseInt(seuilsFixes.getTotalChargesProjet().getSeuilMin().toString()) !=  Integer.parseInt(totalChargesProjetSeuilMin.getText())){
                url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "totalChargesProjetMin" +"&&value="+totalChargesProjetSeuilMin.getText()+"&nomProjet="+nomProjet);
                url.openStream();
                seuilsFixes.getTotalChargesProjet().setSeuilMin(new Integer(Integer.parseInt(totalChargesProjetSeuilMin.getText())));
            }
            
            if(Integer.parseInt(seuilsFixes.getTotalChargesProjet().getSeuilMax().toString()) !=  Integer.parseInt(totalChargesProjetSeuilMax.getText())){
                url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "totalChargesProjetMax" +"&value="+totalChargesProjetSeuilMax.getText()+"&nomProjet="+nomProjet);
                url.openStream();
                seuilsFixes.getTotalChargesProjet().setSeuilMax(new Integer(Integer.parseInt(totalChargesProjetSeuilMax.getText())));
            }
            
            if(Integer.parseInt(seuilsFixes.getTachesTermineesProjet().getSeuilMin().toString()) !=  Integer.parseInt(tacheTermineesProjetSeuilMin.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "tachesTermineesProjetMin" +"&value="+tacheTermineesProjetSeuilMin.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getTachesTermineesProjet().setSeuilMin(new Integer(Integer.parseInt(tacheTermineesProjetSeuilMin.getText())));
            }
            
            if(Integer.parseInt(seuilsFixes.getTachesTermineesProjet().getSeuilMax().toString()) !=  Integer.parseInt(tacheTermineesProjetSeuilMax.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "tachesTermineesProjetMax" +"&value="+tacheTermineesProjetSeuilMax.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getTachesTermineesProjet().setSeuilMax(new Integer(Integer.parseInt(tacheTermineesProjetSeuilMax.getText())));
            }
            if(Float.parseFloat(seuilsFixes.getDureeMoyenneTache().getSeuilMin().toString()) !=  Float.parseFloat(dureeMoyenneProjetSeuilMin.getText())){  
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "dureeMoyenneTacheMin" +"&value="+dureeMoyenneProjetSeuilMin.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getDureeMoyenneTache().setSeuilMin(new Float(Float.parseFloat(dureeMoyenneProjetSeuilMin.getText())));
            }
            
            if(Float.parseFloat(seuilsFixes.getDureeMoyenneTache().getSeuilMax().toString()) !=  Float.parseFloat(dureeMoyenneProjetSeuilMax.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "dureeMoyenneTacheMax" +"&value="+dureeMoyenneProjetSeuilMax.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getDureeMoyenneTache().setSeuilMax(new Float(Float.parseFloat(dureeMoyenneProjetSeuilMax.getText())));
            }
            
            if(Integer.parseInt(seuilsFixes.getNombreParticipants().getSeuilMin().toString()) !=  Integer.parseInt(nombreParticipantProjetSeuilMin.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "nombreParticipantsMin" +"&value="+nombreParticipantProjetSeuilMin.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getNombreParticipants().setSeuilMin(new Integer(Integer.parseInt(nombreParticipantProjetSeuilMin.getText())));
            }
            
            if(Integer.parseInt(seuilsFixes.getNombreParticipants().getSeuilMax().toString()) !=  Integer.parseInt(nombreParticipantProjetSeuilMax.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "nombreParticipantsMax" +"&value="+nombreParticipantProjetSeuilMax.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getNombreParticipants().setSeuilMax(new Integer(Integer.parseInt(nombreParticipantProjetSeuilMax.getText())));
            
            }
            
            if(Integer.parseInt(seuilsFixes.getTotalChargesIteration().getSeuilMin().toString()) !=  Integer.parseInt(totalChargesIterationSeuilMin.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "totalChargesIterationMin" +"&value="+totalChargesIterationSeuilMin.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getTotalChargesIteration().setSeuilMin(new Integer(Integer.parseInt(totalChargesIterationSeuilMin.getText())));
            }
            
            if(Integer.parseInt(seuilsFixes.getTotalChargesIteration().getSeuilMax().toString()) !=  Integer.parseInt(totalChargesIterationSeuilMax.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "totalChargesIterationMax" +"&value="+totalChargesIterationSeuilMax.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getTotalChargesIteration().setSeuilMax(new Integer(Integer.parseInt(totalChargesIterationSeuilMax.getText())));
            }
            
            if(Integer.parseInt(seuilsFixes.getTacheTermineesIteration().getSeuilMin().toString()) !=  Integer.parseInt(tacheTermineesIterationSeuilMin.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "tacheTermineesIterationMin" +"&value="+tacheTermineesIterationSeuilMin.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getTacheTermineesIteration().setSeuilMin(new Integer(Integer.parseInt(tacheTermineesIterationSeuilMin.getText())));
            }
            
            if(Integer.parseInt(seuilsFixes.getTacheTermineesIteration().getSeuilMax().toString()) !=  Integer.parseInt(tacheTermineesIterationSeuilMax.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "tacheTermineesIterationMax" +"&value="+tacheTermineesIterationSeuilMax.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getTacheTermineesIteration().setSeuilMax(new Integer(Integer.parseInt(tacheTermineesIterationSeuilMax.getText()))); 
            }
            
            if(Float.parseFloat(seuilsFixes.getDureeMoyenneIteration().getSeuilMin().toString()) !=  Float.parseFloat(dureeMoyenneIterationSeuilMin.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "dureeMoyenneIterationMin" +"&value="+dureeMoyenneIterationSeuilMin.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getDureeMoyenneIteration().setSeuilMin(new Float(Float.parseFloat(dureeMoyenneIterationSeuilMin.getText())));
            
            }
            if(Float.parseFloat(seuilsFixes.getDureeMoyenneIteration().getSeuilMax().toString()) !=  Float.parseFloat(dureeMoyenneIterationSeuilMax.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "dureeMoyenneIterationMax" +"&value="+dureeMoyenneIterationSeuilMax.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getDureeMoyenneIteration().setSeuilMax(new Float(Float.parseFloat(dureeMoyenneIterationSeuilMax.getText())));
            }
            
            if(Integer.parseInt(seuilsFixes.getNombreParticipantIteration().getSeuilMin().toString()) !=  Integer.parseInt(nombreParticipantIterationSeuilMin.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "nombreParticipantIterationMin" +"&value="+nombreParticipantIterationSeuilMin.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getNombreParticipantIteration().setSeuilMin(new Integer(Integer.parseInt(nombreParticipantIterationSeuilMin.getText())));
            
            }
            
            if(Integer.parseInt(seuilsFixes.getNombreParticipantIteration().getSeuilMax().toString()) !=  Integer.parseInt(nombreParticipantIterationSeuilMax.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "nombreParticipantIterationMax" +"&value="+nombreParticipantIterationSeuilMax.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getNombreParticipantIteration().setSeuilMax(new Integer(Integer.parseInt(nombreParticipantIterationSeuilMax.getText())));
            }
            
            if(Float.parseFloat(seuilsFixes.getChargeMoyenne().getSeuilMin().toString()) !=  Float.parseFloat(chargeMoyenneSeuilMin.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "chargeMoyenneMin" +"&value="+chargeMoyenneSeuilMin.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getChargeMoyenne().setSeuilMin(new Float(Float.parseFloat(chargeMoyenneSeuilMin.getText())));
            
            }
            
            if(Float.parseFloat(seuilsFixes.getChargeMoyenne().getSeuilMax().toString()) !=  Float.parseFloat(chargeMoyenneSeuilMax.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "chargeMoyenneMax" +"&value="+chargeMoyenneSeuilMax.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getChargeMoyenne().setSeuilMax(new Float(Float.parseFloat(chargeMoyenneSeuilMax.getText())));
            }
            
            if(Float.parseFloat(seuilsFixes.getNombreTacheParticipant().getSeuilMin().toString()) !=  Float.parseFloat(nombreTacheParticipantSeuilMin.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "nombreTacheParticipantMin" +"&value="+nombreTacheParticipantSeuilMin.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getNombreTacheParticipant().setSeuilMin(new Float(Float.parseFloat(nombreTacheParticipantSeuilMin.getText())));
            
            }
            
            if(Float.parseFloat(seuilsFixes.getNombreTacheParticipant().getSeuilMax().toString()) !=  Float.parseFloat(nombreTacheParticipantSeuilMax.getText())){
            url = new URL("http://"+P2S.P2S.Preferences.getProperty("host")+":"+P2S.P2S.Preferences.getProperty("port")+"/p2sserver/MAJBDSeuil?login="+login+"&pass="+pass+"&nomChamp="+ "nombreTacheParticipantMax" +"&value="+nombreTacheParticipantSeuilMax.getText()+"&nomProjet="+nomProjet);
            url.openStream();
            seuilsFixes.getNombreTacheParticipant().setSeuilMax(new Float(Float.parseFloat(nombreTacheParticipantSeuilMax.getText())));
            }
            
        } catch(MalformedURLException e1){
	    javax.swing.JOptionPane.showMessageDialog(null, Bundle.getText("ExceptionErrorURL"), Bundle.getText("ExceptionErrorTitle"), javax.swing.JOptionPane.ERROR_MESSAGE) ;
        } catch(IOException e2){
	    javax.swing.JOptionPane.showMessageDialog(null, Bundle.getText("ErrorConnexionServer"), Bundle.getText("ExceptionErrorTitle"), javax.swing.JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        } catch(IllegalArgumentException e3){
            e3.printStackTrace();
	    javax.swing.JOptionPane.showMessageDialog(null, Bundle.getText("ExceptionErrorARGS"), Bundle.getText("ExceptionErrorTitle"), javax.swing.JOptionPane.ERROR_MESSAGE) ;            
        }        
    }//GEN-LAST:event_jButton1ActionPerformed
//GEN-FIRST:event_nombreParticipantProjetSeuilMinActionPerformed
    private void nombreTacheParticipantSeuilMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_nombreParticipantProjetSeuilMinActionPerformed
        try{//GEN-FIRST:event_nombreTacheParticipantSeuilMaxFocusLost
            ancienneValeur2 = ancienneValeur;
            Float.parseFloat(nombreTacheParticipantSeuilMax.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            nombreTacheParticipantSeuilMax.setText(projet.getSeuilFixes().getNombreTacheParticipant().getSeuilMax().toString());
        }
    }//GEN-LAST:event_nombreTacheParticipantSeuilMaxFocusLost
//GEN-FIRST:event_nombreTacheParticipantSeuilMaxFocusGained
    private void nombreTacheParticipantSeuilMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_nombreTacheParticipantSeuilMaxFocusGained
        try{//GEN-FIRST:event_nombreTacheParticipantSeuilMinFocusLost
            ancienneValeur2 = ancienneValeur;
            Float.parseFloat(nombreTacheParticipantSeuilMin.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            nombreTacheParticipantSeuilMin.setText(projet.getSeuilFixes().getNombreTacheParticipant().getSeuilMin().toString());
        }
    }//GEN-LAST:event_nombreTacheParticipantSeuilMinFocusLost
//GEN-FIRST:event_nombreTacheParticipantSeuilMinFocusGained
    private void chargeMoyenneSeuilMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_nombreTacheParticipantSeuilMinFocusGained
        try{//GEN-FIRST:event_chargeMoyenneSeuilMaxFocusLost
            ancienneValeur2 = ancienneValeur;
            Float.parseFloat(chargeMoyenneSeuilMax.getText());
            chargeMoyenneSeuilMax.setText(new Float(Float.parseFloat(chargeMoyenneSeuilMax.getText())).toString());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un flottant", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            chargeMoyenneSeuilMax.setText(projet.getSeuilFixes().getChargeMoyenne().getSeuilMax().toString());
        }
    }//GEN-LAST:event_chargeMoyenneSeuilMaxFocusLost

//GEN-FIRST:event_chargeMoyenneSeuilMaxFocusGained
//GEN-LAST:event_chargeMoyenneSeuilMaxFocusGained
    private void chargeMoyenneSeuilMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chargeMoyenneSeuilMinFocusLost
        try{
            Float.parseFloat(chargeMoyenneSeuilMin.getText());
            chargeMoyenneSeuilMin.setText(new Float(Float.parseFloat(chargeMoyenneSeuilMin.getText())).toString());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un flottant", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            chargeMoyenneSeuilMin.setText(projet.getSeuilFixes().getChargeMoyenne().getSeuilMin().toString());
        }
    }//GEN-LAST:event_chargeMoyenneSeuilMinFocusLost

//GEN-FIRST:event_chargeMoyenneSeuilMinFocusGained
//GEN-LAST:event_chargeMoyenneSeuilMinFocusGained
    private void nombreParticipantIterationSeuilMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreParticipantIterationSeuilMaxFocusLost
        try{
            Integer.parseInt(nombreParticipantIterationSeuilMax.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            nombreParticipantIterationSeuilMax.setText(projet.getSeuilFixes().getNombreParticipantIteration().getSeuilMax().toString());
        }
    }//GEN-LAST:event_nombreParticipantIterationSeuilMaxFocusLost
//GEN-FIRST:event_nombreParticipantIterationSeuilMaxFocusGained
    private void nombreParticipantIterationSeuilMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_nombreParticipantIterationSeuilMaxFocusGained
        try{//GEN-FIRST:event_nombreParticipantIterationSeuilMinFocusLost
            Integer.parseInt(nombreParticipantIterationSeuilMin.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            nombreParticipantIterationSeuilMin.setText(projet.getSeuilFixes().getNombreParticipantIteration().getSeuilMin().toString());
        }
    }//GEN-LAST:event_nombreParticipantIterationSeuilMinFocusLost
//GEN-FIRST:event_nombreParticipantIterationSeuilMinFocusGained
    private void dureeMoyenneIterationSeuilMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_nombreParticipantIterationSeuilMinFocusGained
        try{//GEN-FIRST:event_dureeMoyenneIterationSeuilMaxFocusLost
            Float.parseFloat(dureeMoyenneIterationSeuilMax.getText());
            dureeMoyenneIterationSeuilMax.setText(new Float(Float.parseFloat(dureeMoyenneIterationSeuilMax.getText())).toString());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un flottant", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            dureeMoyenneIterationSeuilMax.setText(projet.getSeuilFixes().getDureeMoyenneIteration().getSeuilMax().toString());
        }
    }//GEN-LAST:event_dureeMoyenneIterationSeuilMaxFocusLost
//GEN-FIRST:event_dureeMoyenneIterationSeuilMaxFocusGained
    private void dureeMoyenneIterationSeuilMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_dureeMoyenneIterationSeuilMaxFocusGained
        try{//GEN-FIRST:event_dureeMoyenneIterationSeuilMinFocusLost
            Float.parseFloat(dureeMoyenneIterationSeuilMin.getText());
            dureeMoyenneIterationSeuilMin.setText(new Float(Float.parseFloat(dureeMoyenneIterationSeuilMin.getText())).toString());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un flottant", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            dureeMoyenneIterationSeuilMin.setText(projet.getSeuilFixes().getDureeMoyenneIteration().getSeuilMin().toString());
        }
    }//GEN-LAST:event_dureeMoyenneIterationSeuilMinFocusLost
//GEN-FIRST:event_dureeMoyenneIterationSeuilMinFocusGained
    private void tacheTermineesIterationSeuilMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_dureeMoyenneIterationSeuilMinFocusGained
        try{//GEN-FIRST:event_tacheTermineesIterationSeuilMaxFocusLost
            Integer.parseInt(tacheTermineesIterationSeuilMax.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            tacheTermineesIterationSeuilMax.setText(projet.getSeuilFixes().getTacheTermineesIteration().getSeuilMax().toString());
        }
    }//GEN-LAST:event_tacheTermineesIterationSeuilMaxFocusLost
//GEN-FIRST:event_tacheTermineesIterationSeuilMaxFocusGained
    private void tacheTermineesIterationSeuilMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_tacheTermineesIterationSeuilMaxFocusGained
        try{//GEN-FIRST:event_tacheTermineesIterationSeuilMinFocusLost
            Integer.parseInt(tacheTermineesIterationSeuilMin.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            tacheTermineesIterationSeuilMin.setText(projet.getSeuilFixes().getTacheTermineesIteration().getSeuilMax().toString());
        }
    }//GEN-LAST:event_tacheTermineesIterationSeuilMinFocusLost
//GEN-FIRST:event_tacheTermineesIterationSeuilMinFocusGained
    private void totalChargesIterationSeuilMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_tacheTermineesIterationSeuilMinFocusGained
        try{//GEN-FIRST:event_totalChargesIterationSeuilMaxFocusLost
            ancienneValeur2 = ancienneValeur;
            Integer.parseInt(totalChargesIterationSeuilMax.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            totalChargesIterationSeuilMax.setText(projet.getSeuilFixes().getTotalChargesIteration().getSeuilMax().toString());
        }
    }//GEN-LAST:event_totalChargesIterationSeuilMaxFocusLost
//GEN-FIRST:event_totalChargesIterationSeuilMaxFocusGained
    private void totalChargesIterationSeuilMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_totalChargesIterationSeuilMaxFocusGained
        try{//GEN-FIRST:event_totalChargesIterationSeuilMinFocusLost
            Integer.parseInt(totalChargesIterationSeuilMin.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            totalChargesIterationSeuilMin.setText(projet.getSeuilFixes().getTotalChargesIteration().getSeuilMin().toString());
        }
    }//GEN-LAST:event_totalChargesIterationSeuilMinFocusLost
//GEN-FIRST:event_totalChargesIterationSeuilMinFocusGained
    private void nombreParticipantProjetSeuilMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_totalChargesIterationSeuilMinFocusGained
        try{//GEN-FIRST:event_nombreParticipantProjetSeuilMaxFocusLost
            Integer.parseInt(nombreParticipantProjetSeuilMax.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            nombreParticipantProjetSeuilMax.setText(projet.getSeuilFixes().getNombreParticipants().getSeuilMax().toString());
        }
    }//GEN-LAST:event_nombreParticipantProjetSeuilMaxFocusLost
//GEN-FIRST:event_nombreParticipantProjetSeuilMaxFocusGained
    private void nombreParticipantProjetSeuilMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_nombreParticipantProjetSeuilMaxFocusGained
        try{//GEN-FIRST:event_nombreParticipantProjetSeuilMinFocusLost
            Integer.parseInt(nombreParticipantProjetSeuilMin.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            nombreParticipantProjetSeuilMin.setText(projet.getSeuilFixes().getNombreParticipants().getSeuilMin().toString());
        }
    }//GEN-LAST:event_nombreParticipantProjetSeuilMinFocusLost
//GEN-FIRST:event_nombreParticipantProjetSeuilMinFocusGained
    private void dureeMoyenneProjetSeuilMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_nombreParticipantProjetSeuilMinFocusGained
        try{//GEN-FIRST:event_dureeMoyenneProjetSeuilMaxFocusLost
            Float.parseFloat(dureeMoyenneProjetSeuilMax.getText());
            dureeMoyenneProjetSeuilMax.setText(new Float(Float.parseFloat(dureeMoyenneProjetSeuilMax.getText())).toString());
      
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un flottant", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            dureeMoyenneProjetSeuilMax.setText(projet.getSeuilFixes().getDureeMoyenneTache().getSeuilMax().toString());
        }
    }//GEN-LAST:event_dureeMoyenneProjetSeuilMaxFocusLost
//GEN-FIRST:event_dureeMoyenneProjetSeuilMaxFocusGained
    private void dureeMoyenneProjetSeuilMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_dureeMoyenneProjetSeuilMaxFocusGained
        try{//GEN-FIRST:event_dureeMoyenneProjetSeuilMinFocusLost
            Float.parseFloat(dureeMoyenneProjetSeuilMin.getText());
            dureeMoyenneProjetSeuilMin.setText(new Float(Float.parseFloat(dureeMoyenneProjetSeuilMin.getText())).toString());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un flottant", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            dureeMoyenneProjetSeuilMin.setText(projet.getSeuilFixes().getDureeMoyenneTache().getSeuilMin().toString());
        }
    }//GEN-LAST:event_dureeMoyenneProjetSeuilMinFocusLost
//GEN-FIRST:event_dureeMoyenneProjetSeuilMinFocusGained
    private void tacheTermineesProjetSeuilMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_dureeMoyenneProjetSeuilMinFocusGained
        try{//GEN-FIRST:event_tacheTermineesProjetSeuilMaxFocusLost
            Integer.parseInt(tacheTermineesProjetSeuilMax.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            tacheTermineesProjetSeuilMax.setText(projet.getSeuilFixes().getTachesTermineesProjet().getSeuilMax().toString());
        }
    }//GEN-LAST:event_tacheTermineesProjetSeuilMaxFocusLost
//GEN-FIRST:event_tacheTermineesProjetSeuilMaxFocusGained
    private void tacheTermineesProjetSeuilMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_tacheTermineesProjetSeuilMaxFocusGained
        try{//GEN-FIRST:event_tacheTermineesProjetSeuilMinFocusLost
            Integer.parseInt(tacheTermineesProjetSeuilMin.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            tacheTermineesProjetSeuilMin.setText(projet.getSeuilFixes().getTachesTermineesProjet().getSeuilMin().toString());
        }
    }//GEN-LAST:event_tacheTermineesProjetSeuilMinFocusLost
//GEN-FIRST:event_tacheTermineesProjetSeuilMinFocusGained
    private void totalChargesProjetSeuilMaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-LAST:event_tacheTermineesProjetSeuilMinFocusGained
        try{//GEN-FIRST:event_totalChargesProjetSeuilMaxFocusLost
            Integer.parseInt(totalChargesProjetSeuilMax.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            totalChargesProjetSeuilMax.setText(projet.getSeuilFixes().getTotalChargesProjet().getSeuilMax().toString());
        }
    }//GEN-LAST:event_totalChargesProjetSeuilMaxFocusLost
                                                       
     private void totalChargesProjetSeuilMinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalChargesProjetSeuilMinFocusLost
        try{
            Integer.parseInt(totalChargesProjetSeuilMin.getText());
        } catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cette valeur doit etre un entier", "Erreur d'arguments", javax.swing.JOptionPane.ERROR_MESSAGE) ;
            totalChargesProjetSeuilMin.setText(projet.getSeuilFixes().getTotalChargesProjet().getSeuilMin().toString());
        }
    }//GEN-LAST:event_totalChargesProjetSeuilMinFocusLost
//GEN-FIRST:event_totalChargesProjetSeuilMinActionPerformed
    private void initSeuil(){//GEN-LAST:event_totalChargesProjetSeuilMinActionPerformed
        SeuilsFixes seuilFixe = projet.getSeuilFixes();//GEN-FIRST:event_dureeMoyenneIterationSeuilMinActionPerformed
//GEN-LAST:event_dureeMoyenneIterationSeuilMinActionPerformed
        //Mise en place des valeurs des seuils pour les indicateurs généraux.//GEN-FIRST:event_totalChargesIterationSeuilMinActionPerformed
        totalChargesProjetSeuilMin.setText(((Integer)seuilFixe.getTotalChargesProjet().getSeuilMin()).toString());//GEN-LAST:event_totalChargesIterationSeuilMinActionPerformed
        totalChargesProjetSeuilMax.setText(((Integer)seuilFixe.getTotalChargesProjet().getSeuilMax()).toString());//GEN-FIRST:event_tacheTermineesIterationSeuilMinActionPerformed
        tacheTermineesProjetSeuilMin.setText(((Integer)seuilFixe.getTachesTermineesProjet().getSeuilMin()).toString());//GEN-LAST:event_tacheTermineesIterationSeuilMinActionPerformed
        tacheTermineesProjetSeuilMax.setText(((Integer)seuilFixe.getTachesTermineesProjet().getSeuilMax()).toString());
        dureeMoyenneProjetSeuilMin.setText(((Float)seuilFixe.getDureeMoyenneTache().getSeuilMin()).toString());
        dureeMoyenneProjetSeuilMax.setText(((Float)seuilFixe.getDureeMoyenneTache().getSeuilMax()).toString());
        nombreParticipantProjetSeuilMin.setText(((Integer)seuilFixe.getNombreParticipants().getSeuilMin()).toString());
        nombreParticipantProjetSeuilMax.setText(((Integer)seuilFixe.getNombreParticipants().getSeuilMax()).toString());
        
        //Mise en place des valeurs des seuils pour les indicateurs d'itération.
        totalChargesIterationSeuilMin.setText(((Integer)seuilFixe.getTotalChargesIteration().getSeuilMin()).toString());
        totalChargesIterationSeuilMax.setText(((Integer)seuilFixe.getTotalChargesIteration().getSeuilMax()).toString());
        tacheTermineesIterationSeuilMin.setText(((Integer)seuilFixe.getTacheTermineesIteration().getSeuilMin()).toString());
        tacheTermineesIterationSeuilMax.setText(((Integer)seuilFixe.getTacheTermineesIteration().getSeuilMax()).toString());
        dureeMoyenneIterationSeuilMin.setText(((Float)seuilFixe.getDureeMoyenneIteration().getSeuilMin()).toString());
        dureeMoyenneIterationSeuilMax.setText(((Float)seuilFixe.getDureeMoyenneIteration().getSeuilMax()).toString());
        nombreParticipantIterationSeuilMin.setText(((Integer)seuilFixe.getNombreParticipantIteration().getSeuilMin()).toString());
        nombreParticipantIterationSeuilMax.setText(((Integer)seuilFixe.getNombreParticipantIteration().getSeuilMax()).toString());
        chargeMoyenneSeuilMin.setText(((Float)seuilFixe.getChargeMoyenne().getSeuilMin()).toString());
        chargeMoyenneSeuilMax.setText(((Float)seuilFixe.getChargeMoyenne().getSeuilMax()).toString());
        nombreTacheParticipantSeuilMin.setText(((Float)seuilFixe.getNombreTacheParticipant().getSeuilMin()).toString());
        nombreTacheParticipantSeuilMax.setText(((Float)seuilFixe.getNombreTacheParticipant().getSeuilMax()).toString());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chargeMoyenne;
    private javax.swing.JTextField chargeMoyenneSeuilMax;
    private javax.swing.JTextField chargeMoyenneSeuilMin;
    private javax.swing.JLabel dureeMoyenneIteration;
    private javax.swing.JTextField dureeMoyenneIterationSeuilMax;
    private javax.swing.JTextField dureeMoyenneIterationSeuilMin;
    private javax.swing.JLabel dureeMoyenneProjet;
    private javax.swing.JTextField dureeMoyenneProjetSeuilMax;
    private javax.swing.JTextField dureeMoyenneProjetSeuilMin;
    private javax.swing.JLabel indicateursGeneraux;
    private javax.swing.JLabel indicateursIterations;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nombreParticipantIteration;
    private javax.swing.JTextField nombreParticipantIterationSeuilMax;
    private javax.swing.JTextField nombreParticipantIterationSeuilMin;
    private javax.swing.JLabel nombreParticipantProjet;
    private javax.swing.JTextField nombreParticipantProjetSeuilMax;
    private javax.swing.JTextField nombreParticipantProjetSeuilMin;
    private javax.swing.JLabel nombreTacheParticipant;
    private javax.swing.JTextField nombreTacheParticipantSeuilMax;
    private javax.swing.JTextField nombreTacheParticipantSeuilMin;
    private javax.swing.JLabel seuilMax;
    private javax.swing.JLabel seuilMin;
    private javax.swing.JLabel tacheTermineesIteration;
    private javax.swing.JTextField tacheTermineesIterationSeuilMax;
    private javax.swing.JTextField tacheTermineesIterationSeuilMin;
    private javax.swing.JLabel tacheTermineesProjet;
    private javax.swing.JTextField tacheTermineesProjetSeuilMax;
    private javax.swing.JTextField tacheTermineesProjetSeuilMin;
    private javax.swing.JLabel totalChargesIteration;
    private javax.swing.JTextField totalChargesIterationSeuilMax;
    private javax.swing.JTextField totalChargesIterationSeuilMin;
    private javax.swing.JLabel totalChargesProjet;
    private javax.swing.JTextField totalChargesProjetSeuilMax;
    private javax.swing.JTextField totalChargesProjetSeuilMin;
    // End of variables declaration//GEN-END:variables
    
    
    void initText(){

                
            totalChargesProjet.setText(Bundle.getText("JPanelSeuils_totalCharges"));
            totalChargesIteration.setText(Bundle.getText("JPanelSeuils_totalChargesTaches"));
            tacheTermineesProjet.setText(Bundle.getText("JPanelSeuils_nbTachesTerminees"));
            tacheTermineesIteration.setText(Bundle.getText("JPanelSeuils_nbTachesTermineesTaches"));
            nombreTacheParticipant.setText(Bundle.getText("JPanelSeuils_nbMoyenTaches"));
            nombreParticipantProjet.setText(Bundle.getText("JPanelSeuils_nbParticipants"));
            nombreParticipantIteration.setText(Bundle.getText("JPanelSeuils_nbParticipants"));
            indicateursIterations.setText(Bundle.getText("JPanelSeuils_titreTaches"));
            indicateursGeneraux.setText(Bundle.getText("JPanelSeuils_titreGeneral"));
            dureeMoyenneProjet.setText(Bundle.getText("JPanelSeuils_duréeMoyenneTâches"));
            dureeMoyenneIteration.setText(Bundle.getText("JPanelSeuils_duréeMoyenneTâches"));
            chargeMoyenne.setText(Bundle.getText("JPanelSeuils_chargeMoyenneParticipants"));
            jButton1.setText(Bundle.getText("JPanelSeuils_bouton"));
    }
}
