/*
 * JPanelInfoSeuil.java
 *
 * Created on 21 mars 2005, 15:46
 */

package P2S.UI.View.JPanel;

import P2S.Model.Projet;
import P2S.Model.SeuilsFixes;

/**
 *
 * @author  Guillaume
 */
public class JPanelInfoSeuil extends javax.swing.JPanel {
    
    private Projet projet;
    
    /** Creates new form JPanelInfoSeuil */
    public JPanelInfoSeuil(Projet proj) {
        projet = proj;
        initComponents();
        initSeuil();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        indicateursGeneraux = new javax.swing.JLabel();
        seuilMin = new javax.swing.JLabel();
        seuilMax = new javax.swing.JLabel();
        totalChargesProjet = new javax.swing.JLabel();
        totalChargesProjetSeuilMin = new javax.swing.JTextField();
        totalChargesProjetSeuilMax = new javax.swing.JTextField();
        tacheTermineesProjet = new javax.swing.JLabel();
        tacheTermineesProjetSeuilMin = new javax.swing.JTextField();
        tacheTermineesProjetSeuilMax = new javax.swing.JTextField();
        dureeMoyenneProjet = new javax.swing.JLabel();
        dureeMoyenneProjetSeuilMin = new javax.swing.JTextField();
        dureeMoyenneProjetSeuilMax = new javax.swing.JTextField();
        nombreParticipantProjet = new javax.swing.JLabel();
        nombreParticipantProjetSeuilMin = new javax.swing.JTextField();
        nombreParticipantProjetSeuilMax = new javax.swing.JTextField();
        indicateursIterations = new javax.swing.JLabel();
        totalChargesIteration = new javax.swing.JLabel();
        totalChargesIterationSeuilMin = new javax.swing.JTextField();
        totalChargesIterationSeuilMax = new javax.swing.JTextField();
        tacheTermineesIteration = new javax.swing.JLabel();
        tacheTermineesIterationSeuilMin = new javax.swing.JTextField();
        tacheTermineesIterationSeuilMax = new javax.swing.JTextField();
        dureeMoyenneIteration = new javax.swing.JLabel();
        dureeMoyenneIterationSeuilMin = new javax.swing.JTextField();
        dureeMoyenneIterationSeuilMax = new javax.swing.JTextField();
        nombreParticipantIteration = new javax.swing.JLabel();
        nombreParticipantIterationSeuilMin = new javax.swing.JTextField();
        nombreParticipantIterationSeuilMax = new javax.swing.JTextField();
        chargeMoyenne = new javax.swing.JLabel();
        chargeMoyenneSeuilMin = new javax.swing.JTextField();
        chargeMoyenneSeuilMax = new javax.swing.JTextField();
        nombreTacheParticipant = new javax.swing.JLabel();
        nombreTacheParticipantSeuilMin = new javax.swing.JTextField();
        nombreTacheParticipantSeuilMax = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indicateursGeneraux.setText("Seuil pour les indicateurs g\u00e9n\u00e9raux :");
        add(indicateursGeneraux, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, -1));

        seuilMin.setText("Min");
        add(seuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 40, -1));

        seuilMax.setText("Max");
        add(seuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        totalChargesProjet.setText("Total des charges");
        add(totalChargesProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, -1));

        totalChargesProjetSeuilMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalChargesProjetSeuilMinActionPerformed(evt);
            }
        });

        add(totalChargesProjetSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 40, -1));

        add(totalChargesProjetSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 40, -1));

        tacheTermineesProjet.setText("Nombre de t\u00e2ches termin\u00e9es");
        add(tacheTermineesProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, -1));

        add(tacheTermineesProjetSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 40, -1));

        add(tacheTermineesProjetSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 40, -1));

        dureeMoyenneProjet.setText("Dur\u00e9e moyenne d'une t\u00e2che");
        add(dureeMoyenneProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, -1));

        add(dureeMoyenneProjetSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 40, -1));

        add(dureeMoyenneProjetSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 40, -1));

        nombreParticipantProjet.setText("Nombre de participants");
        add(nombreParticipantProjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, -1));

        add(nombreParticipantProjetSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 40, -1));

        add(nombreParticipantProjetSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 40, -1));

        indicateursIterations.setText("Seuil pour les indicateurs des t\u00e2ches :");
        add(indicateursIterations, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 200, -1));

        totalChargesIteration.setText("Total des charges");
        add(totalChargesIteration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, -1));

        totalChargesIterationSeuilMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalChargesIterationSeuilMinActionPerformed(evt);
            }
        });

        add(totalChargesIterationSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 40, -1));

        add(totalChargesIterationSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 40, -1));

        tacheTermineesIteration.setText("Nombre de t\u00e2ches termin\u00e9es");
        add(tacheTermineesIteration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 220, -1));

        tacheTermineesIterationSeuilMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacheTermineesIterationSeuilMinActionPerformed(evt);
            }
        });

        add(tacheTermineesIterationSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 40, -1));

        add(tacheTermineesIterationSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 40, -1));

        dureeMoyenneIteration.setText("Dur\u00e9e moyenne des t\u00e2ches");
        add(dureeMoyenneIteration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, -1));

        dureeMoyenneIterationSeuilMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dureeMoyenneIterationSeuilMinActionPerformed(evt);
            }
        });

        add(dureeMoyenneIterationSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 40, -1));

        add(dureeMoyenneIterationSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 40, -1));

        nombreParticipantIteration.setText("Nombre de participants");
        add(nombreParticipantIteration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, -1));

        add(nombreParticipantIterationSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 40, -1));

        add(nombreParticipantIterationSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 40, -1));

        chargeMoyenne.setText("Charge moyenne des participants");
        add(chargeMoyenne, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, -1));

        add(chargeMoyenneSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 40, -1));

        add(chargeMoyenneSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 40, -1));

        nombreTacheParticipant.setText("Nombre moyen de t\u00e2ches par participants");
        add(nombreTacheParticipant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 230, -1));

        add(nombreTacheParticipantSeuilMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 40, -1));

        add(nombreTacheParticipantSeuilMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 40, -1));

    }//GEN-END:initComponents
    
    private void tacheTermineesIterationSeuilMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacheTermineesIterationSeuilMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tacheTermineesIterationSeuilMinActionPerformed
    
    private void totalChargesIterationSeuilMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalChargesIterationSeuilMinActionPerformed
        
    }//GEN-LAST:event_totalChargesIterationSeuilMinActionPerformed
    
    private void dureeMoyenneIterationSeuilMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dureeMoyenneIterationSeuilMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dureeMoyenneIterationSeuilMinActionPerformed
    
    private void totalChargesProjetSeuilMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalChargesProjetSeuilMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalChargesProjetSeuilMinActionPerformed
    
    private void initSeuil(){
        SeuilsFixes seuilFixe = projet.getSeuilFixes();
        
        //Mise en place des valeurs des seuils pour les indicateurs généraux.
        totalChargesProjetSeuilMin.setText(((Integer)seuilFixe.getTotalChargesProjet().getSeuilMin()).toString());
        totalChargesProjetSeuilMax.setText(((Integer)seuilFixe.getTotalChargesProjet().getSeuilMax()).toString());
        tacheTermineesProjetSeuilMin.setText(((Integer)seuilFixe.getTachesTermineesProjet().getSeuilMin()).toString());
        tacheTermineesProjetSeuilMax.setText(((Integer)seuilFixe.getTachesTermineesProjet().getSeuilMax()).toString());
        dureeMoyenneProjetSeuilMin.setText(((Float)seuilFixe.getDureeMoyenneTache().getSeuilMin()).toString());
        dureeMoyenneProjetSeuilMax.setText(((Float)seuilFixe.getDureeMoyenneTache().getSeuilMax()).toString());
        nombreParticipantProjetSeuilMin.setText(((Integer)seuilFixe.getNombreParticipants().getSeuilMin()).toString());
        nombreParticipantProjetSeuilMax.setText(((Integer)seuilFixe.getNombreParticipants().getSeuilMax()).toString());
        
        //Mise en place des valeurs des seuils pour les indicateurs d'itération.
        totalChargesIterationSeuilMin.setText(((Integer)seuilFixe.getTotalChargesIteration().getSeuilMin()).toString());
        totalChargesIterationSeuilMax.setText(((Integer)seuilFixe.getTotalChargesIteration().getSeuilMax()).toString());
        tacheTermineesIterationSeuilMin.setText(((Integer)seuilFixe.getTacheTermineesIteration().getSeuilMin()).toString());
        tacheTermineesIterationSeuilMax.setText(((Integer)seuilFixe.getTacheTermineesIteration().getSeuilMax()).toString());
        dureeMoyenneIterationSeuilMin.setText(((Float)seuilFixe.getDureeMoyenneIteration().getSeuilMin()).toString());
        dureeMoyenneIterationSeuilMax.setText(((Float)seuilFixe.getDureeMoyenneIteration().getSeuilMax()).toString());
        nombreParticipantIterationSeuilMin.setText(((Integer)seuilFixe.getNombreParticipantIteration().getSeuilMin()).toString());
        nombreParticipantIterationSeuilMax.setText(((Integer)seuilFixe.getNombreParticipantIteration().getSeuilMax()).toString());
        chargeMoyenneSeuilMin.setText(((Float)seuilFixe.getChargeMoyenne().getSeuilMin()).toString());
        chargeMoyenneSeuilMax.setText(((Float)seuilFixe.getChargeMoyenne().getSeuilMax()).toString());
        nombreTacheParticipantSeuilMin.setText(((Integer)seuilFixe.getNombreTacheParticipant().getSeuilMin()).toString());
        nombreTacheParticipantSeuilMax.setText(((Integer)seuilFixe.getNombreTacheParticipant().getSeuilMax()).toString());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chargeMoyenne;
    private javax.swing.JTextField chargeMoyenneSeuilMax;
    private javax.swing.JTextField chargeMoyenneSeuilMin;
    private javax.swing.JLabel dureeMoyenneIteration;
    private javax.swing.JTextField dureeMoyenneIterationSeuilMax;
    private javax.swing.JTextField dureeMoyenneIterationSeuilMin;
    private javax.swing.JLabel dureeMoyenneProjet;
    private javax.swing.JTextField dureeMoyenneProjetSeuilMax;
    private javax.swing.JTextField dureeMoyenneProjetSeuilMin;
    private javax.swing.JLabel indicateursGeneraux;
    private javax.swing.JLabel indicateursIterations;
    private javax.swing.JLabel nombreParticipantIteration;
    private javax.swing.JTextField nombreParticipantIterationSeuilMax;
    private javax.swing.JTextField nombreParticipantIterationSeuilMin;
    private javax.swing.JLabel nombreParticipantProjet;
    private javax.swing.JTextField nombreParticipantProjetSeuilMax;
    private javax.swing.JTextField nombreParticipantProjetSeuilMin;
    private javax.swing.JLabel nombreTacheParticipant;
    private javax.swing.JTextField nombreTacheParticipantSeuilMax;
    private javax.swing.JTextField nombreTacheParticipantSeuilMin;
    private javax.swing.JLabel seuilMax;
    private javax.swing.JLabel seuilMin;
    private javax.swing.JLabel tacheTermineesIteration;
    private javax.swing.JTextField tacheTermineesIterationSeuilMax;
    private javax.swing.JTextField tacheTermineesIterationSeuilMin;
    private javax.swing.JLabel tacheTermineesProjet;
    private javax.swing.JTextField tacheTermineesProjetSeuilMax;
    private javax.swing.JTextField tacheTermineesProjetSeuilMin;
    private javax.swing.JLabel totalChargesIteration;
    private javax.swing.JTextField totalChargesIterationSeuilMax;
    private javax.swing.JTextField totalChargesIterationSeuilMin;
    private javax.swing.JLabel totalChargesProjet;
    private javax.swing.JTextField totalChargesProjetSeuilMax;
    private javax.swing.JTextField totalChargesProjetSeuilMin;
    // End of variables declaration//GEN-END:variables
    
}
