/*
 * JPanelInfoGenProjet.java
 *
 * Created on 26 janvier 2005, 01:15
 */

package P2S.UI.View.JPanel;

import P2S.Control.Bundle.Bundle;
import P2S.Model.Projet;
import java.text.DateFormat;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 * JPanel affichant les informations generales d'un projet
 * @author Fabien
 */
public class JPanelInfoGenProjet extends javax.swing.JPanel {
    
    /**
     * Creates new form JPanelInfoGenProjet
     * @param proj projet à afficher
     */
    public JPanelInfoGenProjet(Projet proj) {
        initComponents();
        
        // Initialisation du texte des labels
        initText();
        
        // On affiche les infos du projet
        this.LabelNomProjet.setText(proj.getNom());
        DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.FULL, Locale.getDefault());
        this.LabelDateDebut.setText(dateFormat.format(proj.getDateDebut()));
        this.LabelDateFin.setText(dateFormat.format(proj.getDateFin()));
        this.TextAreaDescription.setText(proj.getDescription());
        this.TextAreaDescription.setEditable(false);       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        JButtonAlerte = new javax.swing.JButton();
        LabelStaticNomProjet = new javax.swing.JLabel();
        LabelStaticDateDebut = new javax.swing.JLabel();
        LabelStaticDateFin = new javax.swing.JLabel();
        LabelStaticDescription = new javax.swing.JLabel();
        LabelNomProjet = new javax.swing.JLabel();
        LabelDateDebut = new javax.swing.JLabel();
        LabelDateFin = new javax.swing.JLabel();
        TextAreaDescription = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        JButtonAlerte.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(JButtonAlerte, gridBagConstraints);

        LabelStaticNomProjet.setText("Nom du projet : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(LabelStaticNomProjet, gridBagConstraints);

        LabelStaticDateDebut.setText("Date de d\u00e9but : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(LabelStaticDateDebut, gridBagConstraints);

        LabelStaticDateFin.setText("Date de fin : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(LabelStaticDateFin, gridBagConstraints);

        LabelStaticDescription.setText("Description : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(LabelStaticDescription, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(LabelNomProjet, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(LabelDateDebut, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(LabelDateFin, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        add(TextAreaDescription, gridBagConstraints);

    }//GEN-END:initComponents
    
    private void initText()
    {        
        this.LabelStaticNomProjet.setText(Bundle.getText("JPanelInfoGenProjet_JLabel_NomProjet"));
        this.LabelStaticDateDebut.setText(Bundle.getText("JPanelInfoGenProjet_JLabel_DateDebut"));
        this.LabelStaticDateFin.setText(Bundle.getText("JPanelInfoGenProjet_JLabel_DateFin"));
        this.LabelStaticDescription.setText(Bundle.getText("JPanelInfoGenProjet_JLabel_Description"));
        this.JButtonAlerte.setText(Bundle.getText("JPanelInfoGenProjet_JButton_Alerte"));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAlerte;
    private javax.swing.JLabel LabelDateDebut;
    private javax.swing.JLabel LabelDateFin;
    private javax.swing.JLabel LabelNomProjet;
    private javax.swing.JLabel LabelStaticDateDebut;
    private javax.swing.JLabel LabelStaticDateFin;
    private javax.swing.JLabel LabelStaticDescription;
    private javax.swing.JLabel LabelStaticNomProjet;
    private javax.swing.JTextArea TextAreaDescription;
    // End of variables declaration//GEN-END:variables
    
}
