/*
 * PanelTousLesProjets.java
 *
 * Created on 27 janvier 2005, 20:04
 */

package P2S.UI.View.JPanel;

import P2S.Model.Projet;
import java.util.Vector;
import javax.swing.JLabel;

/**
 * JPanel affichant les informations sur l'ensemble des projets
 * @author Fabien
 */
public class JPanelTousLesProjets extends javax.swing.JPanel {
    
    /**
     * Creates new form PanelTousLesProjets
     * @param listeProjets liste des projets du superviseur
     */
    public JPanelTousLesProjets(Vector listeProjets) {
        initComponents();
               
        java.awt.GridBagConstraints gridBagConstraints;
        
        // On parcourt tous les projets et on les ajoute au panel
        int i;
        for(i=0;i<listeProjets.size();i++)
        {
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = i;
            gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
            gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
            add(new JLabel(((Projet)listeProjets.get(i)).getNom()), gridBagConstraints);
        }
        
        // On ajoute ce label vide pour mettre en forme le panel
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = i;        
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(new JLabel(""), gridBagConstraints);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.GridBagLayout());

    }//GEN-END:initComponents
    
    private void initText()
    {
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
