/*
 * JPanelIndicTachesMembre.java
 *
 * Created on 26 février 2005, 10:57
 */

package P2S.UI.View.JPanel;

import P2S.Control.Bundle.Bundle;
import P2S.Model.IndicateursTacheMembre;
import P2S.UI.View.JDialog.ModeleTableMesure;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author  Conde Mike K
 */
public class JPanelIndicTachesMembre extends javax.swing.JPanel {
    
    private String[] nomsColonnes = {Bundle.getText("JTableIndicTachesColonne1"), Bundle.getText("JTableIndicTachesColonne2")} ;
    private Object[][] donnees = null ;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    
    /** Creates new form JPanelIndicTachesMembre */
    public JPanelIndicTachesMembre (Vector indicateursTache) {
        
        // initialisation des donnees
        initComponents ();
        
        donnees = new Object[indicateursTache.size()][2] ;
        for (int i = 0 ; i < donnees.length ; i++)
        {
            if (indicateursTache.get(i) instanceof IndicateursTacheMembre)
            {
                donnees[i][0] = ((IndicateursTacheMembre)indicateursTache.get(i)).getNom() ;
                donnees[i][1] = ((IndicateursTacheMembre)indicateursTache.get(i)).getTempsPasse() ;
            }
        }
        
        ModeleTableMesure tableModel = new ModeleTableMesure(donnees, nomsColonnes) ;        
        table = new JTable(tableModel) ;
        tableScrollPane = new JScrollPane(table) ;
        add(tableScrollPane, java.awt.BorderLayout.CENTER);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
        
}
