/*
 * JPanelInfoProbleme.java
 *
 * Created on 8 mars 2005, 10:26
 */

package P2S.UI.View.JPanel;

import P2S.Control.Bundle.Bundle;
import P2S.Model.Probleme;
import P2S.UI.View.JDialog.ModeleTableMesure;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author  Conde Mike K
 */
public class JPanelInfoProbleme extends javax.swing.JPanel {
    
    private String[] nomsColonnes = {Bundle.getText("JTableProblemesColonne1"), Bundle.getText("JTableProblemesColonne2"),Bundle.getText("JTableProblemesColonne3"),Bundle.getText("JTableProblemesColonne4")} ;
    private Object[][] donnees = null ;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    
    /** Creates new form JPanelInfoProbleme */
    public JPanelInfoProbleme (Vector problemes) {
	initComponents ();
	
	
	donnees = new Object[problemes.size()][4] ;
        for (int i = 0 ; i < donnees.length ; i++)
        {
            if (problemes.get(i) instanceof Probleme)
            {
                
                if(((Probleme)problemes.get(i)).getNom() != null)
                    donnees[i][0] = ((Probleme)problemes.get(i)).getNom() ;
                else
                    donnees[i][0] = "N/C"; 
                
                if(((Probleme)problemes.get(i)).getCause() != null)
                    donnees[i][1] = ((Probleme)problemes.get(i)).getCause() ;
                else
                    donnees[i][1] = "N/C"; 
                if(((Probleme)problemes.get(i)).getDebut() != null)
                    donnees[i][2] = ((Probleme)problemes.get(i)).getDebut() ;
                else
                    donnees[i][2] = "N/C"; 
                if(((Probleme)problemes.get(i)).getFin() != null)
                    donnees[i][3] = ((Probleme)problemes.get(i)).getFin() ;
                else
                    donnees[i][3] = "N/C"; 
            }
        }
        
        
        ModeleTableMesure tableModel = new ModeleTableMesure(donnees, nomsColonnes) ;
        table = new JTable(tableModel) ;
        tableScrollPane = new JScrollPane(table) ;
	add(tableScrollPane, java.awt.BorderLayout.CENTER);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
