/*
 * JPanelInfoGenMembre.java
 *
 * Created on 26 janvier 2005, 02:22
 */

package P2S.UI.View.JPanel;

import P2S.Control.Bundle.Bundle;
import P2S.Model.Membre;
import javax.swing.JLabel;

/**
 * JPanel contenant les informations generales sur un membres
 * @author Fabien
 */
public class JPanelInfoGenMembre extends javax.swing.JPanel {
    
    /**
     * Creates new form JPanelInfoGenMembre
     * @param membre membre a afficher
     */
    public JPanelInfoGenMembre(Membre membre) {
        initComponents();
        
        // Initialisation du texte des labels
        initText();
        
        // On affiche les infos du membre
        this.LabelNom.setText(membre.getNom());
        this.LabelPrenom.setText(membre.getPrenom());
        this.LabelAdresse.setText(membre.getAdresse());
        this.LabelTelephone.setText(membre.getTelephone());
        this.LabelEMail.setText(membre.getEmail());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        LabelStaticNom = new javax.swing.JLabel();
        LabelStaticPrenom = new javax.swing.JLabel();
        LabelStaticAdresse = new javax.swing.JLabel();
        LabelStaticTelephone = new javax.swing.JLabel();
        LabelStaticEMail = new javax.swing.JLabel();
        LabelNom = new javax.swing.JLabel();
        LabelPrenom = new javax.swing.JLabel();
        LabelAdresse = new javax.swing.JLabel();
        LabelTelephone = new javax.swing.JLabel();
        LabelEMail = new javax.swing.JLabel();
        LabelVide = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        LabelStaticNom.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(LabelStaticNom, gridBagConstraints);

        LabelStaticPrenom.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(LabelStaticPrenom, gridBagConstraints);

        LabelStaticAdresse.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(LabelStaticAdresse, gridBagConstraints);

        LabelStaticTelephone.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(LabelStaticTelephone, gridBagConstraints);

        LabelStaticEMail.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(LabelStaticEMail, gridBagConstraints);

        LabelNom.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(LabelNom, gridBagConstraints);

        LabelPrenom.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(LabelPrenom, gridBagConstraints);

        LabelAdresse.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(LabelAdresse, gridBagConstraints);

        LabelTelephone.setText("jLabel4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(LabelTelephone, gridBagConstraints);

        LabelEMail.setText("jLabel5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        add(LabelEMail, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(LabelVide, gridBagConstraints);

    }//GEN-END:initComponents
             
    private void initText()
    {
        this.LabelStaticNom.setText(Bundle.getText("JPanelInfoMembre_JLabel_Nom"));
        this.LabelStaticPrenom.setText(Bundle.getText("JPanelInfoMembre_JLabel_Prenom"));
        this.LabelStaticAdresse.setText(Bundle.getText("JPanelInfoMembre_JLabel_Adresse"));
        this.LabelStaticTelephone.setText(Bundle.getText("JPanelInfoMembre_JLabel_Telephone"));
        this.LabelStaticEMail.setText(Bundle.getText("JPanelInfoMembre_JLabel_EMail"));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAdresse;
    private javax.swing.JLabel LabelEMail;
    private javax.swing.JLabel LabelNom;
    private javax.swing.JLabel LabelPrenom;
    private javax.swing.JLabel LabelStaticAdresse;
    private javax.swing.JLabel LabelStaticEMail;
    private javax.swing.JLabel LabelStaticNom;
    private javax.swing.JLabel LabelStaticPrenom;
    private javax.swing.JLabel LabelStaticTelephone;
    private javax.swing.JLabel LabelTelephone;
    private javax.swing.JLabel LabelVide;
    // End of variables declaration//GEN-END:variables
    
}
