/*
 * JPanelIndicTachesMembre.java
 *
 * Created on 26 février 2005, 10:57
 */

package P2S.UI.View.JPanel;

import P2S.Control.Bundle.Bundle;
import P2S.Model.IndicateursTacheMembre;
import P2S.UI.View.JDialog.ModeleTableMesure;
import java.awt.Component;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JFormattedTextField;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author  Conde Mike K
 */
public class JPanelIndicTachesMembre extends javax.swing.JPanel {
    
    private String[] nomsColonnes = {Bundle.getText("JTableIndicTachesColonne1"), Bundle.getText("JTableIndicTachesColonne2"), Bundle.getText("JTableIndicTachesColonne3")} ;
    private Object[][] donnees = null ;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScrollPane;
    
    /** Creates new form JPanelIndicTachesMembre */
    public JPanelIndicTachesMembre (Vector indicateursTache) {
        
        // initialisation des donnees
        initComponents ();
        
        donnees = new Object[indicateursTache.size()][3] ;
        for (int i = 0 ; i < donnees.length ; i++)
        {
            if (indicateursTache.get(i) instanceof IndicateursTacheMembre)
            {
                donnees[i][0] = ((IndicateursTacheMembre)indicateursTache.get(i)).getNom() ;
                donnees[i][1] = new Integer(((IndicateursTacheMembre)indicateursTache.get(i)).getCharges()) ;
                donnees[i][2] = ((IndicateursTacheMembre)indicateursTache.get(i)).getNomProjet();
            }
        }
        
        ModeleTableMesure tableModel = new ModeleTableMesure(donnees, nomsColonnes) ;        
        table = new JTable(tableModel) ;
	table.setDefaultRenderer(Integer.class, new NumericRenderer()) ;
        tableScrollPane = new JScrollPane(table) ;
        add(tableScrollPane, java.awt.BorderLayout.CENTER);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents
    
    
    /** classe NumericRenderer
    * @author C Mike K
    * @version 1.0
    */
   class NumericRenderer implements TableCellRenderer
   {
      private JFormattedTextField numericField = new JFormattedTextField() ;

      public NumericRenderer()
      {
         numericField.setHorizontalAlignment(JTextField.RIGHT) ;
         numericField.setBorder(BorderFactory.createEmptyBorder()) ;
      }

      public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column)
      {
         numericField.setValue(value + " " +Bundle.getText("Constante_heures")) ;
         return numericField ;
      }

   } // fin de la classe NumericRenderer
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
        
}
